### ISSUE TITLE
Unable to edit out a file from a response.

### ISSUE THREAD

**Issue by ranshaa05** [nextcord/nextcord#1016]
### Summary

I am unable to remove a file attachment from a response message.

### Reproduction Steps

- send an interaction.response.send_message() with a file attached.
- edit the message with interaction.response.send__message().edit(content=None, file=None)

### Minimal Reproducible Code

```python
original_message = await interaction.response.send_message(content="hello", file=nextcord.File(fp=fp)
await original_message.edit(content=None, file=None)
```

### Expected Results

the content and file should be removed from the message.

### Actual Results

the content is removed, but file requires a pathlike object that has a "filename" attribute, so it throws an exception.
this happens with "file=nextcord.File(None)" as well.

### Intents

intents=nextcord.Intents().all()

### System Information

- Python v3.11.2-final
- nextcord v2.4.1-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ranshaa05** [comment]
> Have you tried `attachments=[]`?

oh that seems to work just fine. thanks!
i do still think file=None should work as well though.

**Comment by ooliver1** [comment]
`file` and `files` use the Discord `files` field, which [states](https://discord.com/developers/docs/resources/channel#edit-message):

> Any provided files will be **appended** to the message. To remove or replace files you will have to supply the `attachments` field which specifies the files to retain on the message after edit.
