### ISSUE TITLE
ForumChannel and Thread returning wrong ForumTags

### ISSUE THREAD

**Issue by Fenix5fire** [nextcord/nextcord#1019]
### Summary

ForumChannel and Thread returning wrong ForumTags

### Reproduction Steps

Get Thread and ForumChannel in any way and try to get ForumTags from it

### Expected Results

Get actual ForumTags from forum channels

### Actual Results

ForumChannel.available_tags only returns last one
Thread.applied_tags and Thread.applied_tag_ids will return empty list
Actually got all data from Discord according to logs, but can't access it in my code

### Intents

all

### System Information

- Python v3.11.2-final
- nextcord v2.4.1-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

**Found bugs in code:**

- ForumTag dict (ForumChannel._available_tags) has been generated with data["id"] instead of tag["id"] as keys which lead to only saving last loaded tag by wrong id. Must be `int(tag["id"]): ForumTag.from_data(tag) for tag in data.get("available_tags", [])`:

https://github.com/nextcord/nextcord/blob/8a04ed3b4ca72b48d27e2af1ecfe380b9f8f32c1/nextcord/channel.py#L964

- Key "applied_thread_tags" does not exist in thread data, which lead to losing all tags when getting Thread. Existing key - 
"applied_tags". Must be `int(tag_id) for tag_id in data.get("applied_tags", [])`:

https://github.com/nextcord/nextcord/blob/8a04ed3b4ca72b48d27e2af1ecfe380b9f8f32c1/nextcord/threads.py#L181

Pull-Request failed by Pyright for some reason, but fix is tested and works in 2.4.1

**Comment by EmreTech** [comment]
If you found bugs in the code, it would be helpful to open a PR to fix the issues.

**Comment by Fenix5fire** [comment]
> If you found bugs in the code, it would be helpful to open a PR to fix the issues.

As I said, it failed checks for reason, which I am completely not responsible to. That "line 964" got None instead of Snowflake in payload when I haven't touched it in any way, just fixing a typo. Also those fixes discovered to be not enough to fully fix the issue, cuz even with them Thread.edit() function does not update ForumTags in cache

**Comment by ooliver1** [comment]
> > If you found bugs in the code, it would be helpful to open a PR to fix the issues.
> 
> As I said, it failed checks for reason, which I am completely not responsible to. That "line 964" got None instead of Snowflake in payload when I haven't touched it in any way, just fixing a typo. Also those fixes discovered to be not enough to fully fix the issue, cuz even with them Thread.edit() function does not update ForumTags in cache
> 
> Recreated PR again: #1021
> 
> ```
>  /home/runner/work/nextcord/nextcord/nextcord/channel.py:964:17 - error: Argument of type "Snowflake | None" cannot be assigned to parameter "__x" of type "ReadableBuffer | str | SupportsInt | SupportsIndex | SupportsTrunc" in function "__new__"
>    Type "Snowflake | None" cannot be assigned to type "ReadableBuffer | str | SupportsInt | SupportsIndex | SupportsTrunc"
>      Type "None" cannot be assigned to type "ReadableBuffer | str | SupportsInt | SupportsIndex | SupportsTrunc"
>        Type "None" cannot be assigned to type "str"
>        Type "None" cannot be assigned to type "ReadOnlyBuffer"
>        Type "None" cannot be assigned to type "bytearray"
>        Type "None" cannot be assigned to type "memoryview"
>        Type "None" cannot be assigned to type "array[Any]"
>        Type "None" cannot be assigned to type "mmap"
>    ... (reportGeneralTypeIssues)
> 1 error, 0 warnings, 0 informations 
> ```

I mentioned this a couple of times in the help thread

https://github.com/nextcord/nextcord/blob/8a04ed3b4ca72b48d27e2af1ecfe380b9f8f32c1/nextcord/types/channel.py#L154

This should not be optional, I'm not sure why it is.

```patch
From c886fdce4896f583806725b6136978004ebc6160 Mon Sep 17 00:00:00 2001
From: Oliver Wilkes <oliverwilkes2006@icloud.com>
Date: Sun, 26 Mar 2023 22:21:56 +0100
Subject: [PATCH] typing(types): make ForumTag.id not optional

---
 nextcord/types/channel.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/nextcord/types/channel.py b/nextcord/types/channel.py
index 5f6ab52d..2b1974b8 100644
--- a/nextcord/types/channel.py
+++ b/nextcord/types/channel.py
@@ -151,7 +151,7 @@ class StageInstance(TypedDict):
 
 
 class ForumTag(TypedDict):
-    id: Optional[Snowflake]
+    id: Snowflake
     name: str
     moderated: bool
     emoji_id: NotRequired[Optional[Snowflake]]
-- 
2.37.2
```

**Comment by EmreTech** [comment]
Reopening since the underlying issue with the library hasn't been resolved yet.
