### ISSUE TITLE
Unable to delete interaction message by using delete_original_message() & unknown webhook

### ISSUE THREAD

**Issue by cgoulart35** [nextcord/nextcord#1059]
### Summary

Unable to delete interaction message by using delete_original_message()

### Reproduction Steps

The following code below is not working for me as I am getting an error "TypeError: Files parameter must be a list of type File".

```
    @nextcord.slash_command(name = "umbrella", description = "umbrella description")
    async def umbrellaSlash(self, interaction: nextcord.Interaction):
        await interaction.delete_original_message(delay = 30)
```

I also tried without a delay specified as a method argument, but then I get this error:
    "Command raised an exception: NotFound: 404 Not Found (error code: 10015): Unknown Webhook"

### Minimal Reproducible Code

```python
@nextcord.slash_command(name = "umbrella", description = "umbrella description")
    async def umbrellaSlash(self, interaction: nextcord.Interaction):
        await interaction.delete_original_message(delay = 30)
```

### Expected Results

I would expect to be able to delete the original message successfully after the specified delay.

### Actual Results

Unable to call the delete_original_message method to set this delete up without errors.

### Intents

nextcord.Intents.all()

### System Information

# python -m nextcord -v
- Python v3.9.7-final
- nextcord v2.4.0-final
- aiohttp v3.8.4
- system info: Linux 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020

(docker container)

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Soheab** [comment]
I don't think the provided error belongs to that code. Please provide a full traceback if that's the case.

Other than that... which message are you trying to delete? A slash command was invoked then `delete_original_message` was called. There is no message here. `delete_original_message` is for deleting any responses to the interaction, which you can send using `interaction.response.send_message` or even `interaction.response.defer` (`with_message` is always True for slash interactions)

**Comment by cgoulart35** [comment]
Hello @Soheab,

I will try to get you a stack trace if I can find one.

Basically I have this regular command (normal @commands.command which uses a Context and not an Interaction) and what it does is deletes the Context's message after x seconds. Here is the way I do this:

`await context.message.delete(delay = 60)`

I created a new command that is basically a wrapper of the this command, but instead it is a slash command (I am adding new @nextcord.slash_command functionality). So the end goal is basically to have this command do the same thing, but with an interaction instead of a context; to delete the message that invoked the command after a certain amount of time. I tried doing that with this code:

`await context.delete_original_message(delay = 60)`

Is it not possible to delete the user's original message / the message that invoked the command for slash command Interactions?

**Comment by Soheab** [comment]
Unlike prefix commands, slash commands are technically not invoked from a message. 

You have to specifically choose the command from the `/` menu and then an interaction callback is sent to the bot which then responds to it which results in a "response message" with the command name at top and any content fields below. That "response message" can be deleted using:
```py
await interaction.delete_original_message(...)
```
`response.defer()` and `interaction.followup.send` are also responses.

If the interaction token is still valid. (15 mins)

Regular commands are handled by the library using the `on_message` event, that's why the `messages and message_content` intents are required for them.
