### ISSUE TITLE
Adding reactions, but message.reactions is returning "[]"

### ISSUE THREAD

**Issue by sairam4123** [nextcord/nextcord#106]
### Link

https://github.com/Rapptz/discord.py/issues/1686

**Comment by ooliver1** [comment]
```py
await _message.add_reaction(":smile:")
newmsg = await _channel.fetch_message(_message.id)
message.reactions
```
In jsk, shows new reactions, you have to get the new object like Danny said

**Comment by ooliver1** [comment]
wontfix, as said in that issue its too complex to be worth it for now, anyone: feel free to PR a fix but it wont be directly added
