### ISSUE TITLE
Add Discord's new "display name" to the user object

### ISSUE THREAD

**Issue by SteffoSpieler** [nextcord/nextcord#1060]
### Summary

Discord added the "display name" to the user profile a few weeks ago, nextcord doesn't support it yet.

### What is the feature request for?

The core library

### The Problem

Discord added the field "Display Name" to the user profile a few weeks ago, which is internally known as "global_name" ([source](https://discord.com/channels/881118111967883295/881118112492191796/1106203571684397088)).
As the username change rolls out to normal users now, it happens more and more often that a user will see their user-tag instead of their display name in bot responses.

### The Ideal Solution

Add the field "global_name" or reuse the field "display_name" in the User object.

### Additional Context

I haven't seen any pull request or issue yet, eventhough that change of discord is already known for a "longer" time now.

**Comment by spifory** [comment]
Since the documentation has been merged for this, I'd like to be assigned to implementing this
