### ISSUE TITLE
datetime.datetime.utcnow is deprecated in Python 3.12

### ISSUE THREAD

**Issue by DenverCoder1** [nextcord/nextcord#1062]
See https://github.com/python/cpython/issues/103857

`utils.utcnow()` creates a timezone-aware datetime in the recommended way so it is fine to use as an alternative in most cases.

For an exact replacement, `utils.utcnow().replace(tzinfo=None)` can be used.

Most instances of `utcnow` and `utcfromtimestamp` were already fixed prior to the creation of nextcord, however one was still found.

```diff
index 725f498a76..c40a6ebbae 100644
--- a/nextcord/member.py
+++ b/nextcord/member.py
@@ -801,7 +801,7 @@ async def edit(
                 if not suppress:
                     voice_state_payload[
                         "request_to_speak_timestamp"
-                    ] = datetime.datetime.utcnow().isoformat()
+                    ] = utils.utcnow().isoformat()
                 await http.edit_voice_state(guild_id, self.id, voice_state_payload)
```

**Comment by EmreTech** [comment]
I found another instance in the same file:

https://github.com/nextcord/nextcord/blob/b3b249e313adb46de76ce35da1cf65aff3769c3d/nextcord/member.py#L854
