### ISSUE TITLE
Issues with: Inter(action).response.defer() and Inter(action).response.send()

### ISSUE THREAD

**Issue by Bradly7412** [nextcord/nextcord#1073]
### Summary

Constant error 10062: Unknown Interaction

### Reproduction Steps

Created discord music bot for friends. Has flawlessly in the past but over time it has just become annoying because it only really works half the time.

When it fails it just completely fails and does not anything and most of the time just completely unresponsive.

### Minimal Reproducible Code

```python
(09:27:22) [INFO]: (*******************) *********: /leave 
Ignoring exception in command <nextcord.application_command.SlashApplicationCommand object at 0x7f34fd5e7ee0>:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/application_command.py", line 890, in invoke_callback_with_hooks
    await self(interaction, *args, **kwargs)
  File "/home/container/bot.py", line 296, in leave
    await inter.send(embed=embed)
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/interactions.py", line 540, in send
    return await self.response.send_message(
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/interactions.py", line 896, in send_message
    await adapter.create_interaction_response(
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/webhook/async_.py", line 190, in request
    raise NotFound(response, data)
nextcord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

nextcord.errors.ApplicationInvokeError: Command raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction

292 else:
293     embed=nextcord.Embed(title="Leaving!", color=0xe100ff)
294     embed.add_field(name="Any Issues ", value="[Click-Here](**********************)", inline=False)
295     embed.set_footer(text="By *********")
296     await inter.send(embed=embed)
297     await inter.guild.voice_client.disconnect()
298     try:
299         QUEUE[inter.guild.id] = []
300     except:
301         pass
```

### Expected Results

I was expecting the bot to leave the voice channel and respond with a simple embed to show that the bot left with a simple message

### Actual Results

Failed to leave and continued playing music in the VC

### Intents

Currently using: guilds and voice_states

### System Information

nextcord: 2.4.1
python 3.9.17

Hosted on a container using Pterodactyl panel

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This is quite annoying wont lie
Not sure when this was fine but as I said recently it has just become broken 50/50 sometimes it works and then fails the other half

**Comment by alentoghostflame** [comment]
Is there anything that could be delaying the interaction response being sent? Interactions timeout in 3 seconds unless deferred.

**Comment by Bradly7412** [comment]
Currently there is nothing delaying the response. it is just the `inter.send()`. if i were to add `inter.response.defer()` then it would also seem to error out with 10062

**Comment by alentoghostflame** [comment]
so if the very first thing you do in the function is `await inter.response.defer()`, it still errors?
I would like to see the entire function if possible, preferably with this pasting site: https://paste.nextcord.dev/

**Comment by Bradly7412** [comment]
it is over at https://paste.nextcord.dev/?id=168731350554715

**Comment by ooliver1** [comment]
This is not a nextcord issue, we do not know what your functions do before and they are likely delaying a response.
