### ISSUE TITLE
Let nextcord.utils.format_dt also take a timestamp instead of only datetime

### ISSUE THREAD

**Issue by H4ckerxx44** [nextcord/nextcord#1085]
### Summary

Let the `format_dt` function from `nextcord.utils` also be able to work with unix timestamps 

### What is the feature request for?

The core library

### The Problem

I have to either manually format them or convert something to a python `datetime` object just for the sake of using the `format_dt` function

### The Ideal Solution

Let `nextcord.utils.format_dt(...)` also take unix timestamps instead of only `datetime` objects, especially when the `format_dt` function just calls `.timestamp()` on the supplied `datetime` object anyways

### The Current Solution

Manually formatting it when not converting it to a `datetime` object just to be able to use this function

**Comment by spifory** [comment]
The idea's cool, but wouldn't that be inconsistent with the name of the function? Since it's `format_dt` (format datetime)

**Comment by teaishealthy** [comment]
This should be it's own function which format_dt can then use. Something like format_ts or format_timestamp

**Comment by H4ckerxx44** [comment]
Or, perhaps, create something like `to_discord_timestamp(a, b)` whereas `b` is a format specifier and `a` is either a datetime or int?
