### ISSUE TITLE
Implement the context menu command message type

### ISSUE THREAD

**Issue by TAG-Epic** [nextcord/nextcord#109]
### Link

https://github.com/discord/discord-api-docs/pull/3651

**Comment by MoonlightCapital** [comment]
Onto it! This will be released when I publish my code for slash commands.

https://github.com/MoonlightCapital/nextcord/commit/bf743a14107aceb8ff9ff1ed7f615d2269429461

**Comment by alentoghostflame** [comment]
This is implemented by now, correct?

**Comment by TAG-Epic** [comment]
@alentoghostflame nope.
