### ISSUE TITLE
Forum Thread edit tag event is not captured

### ISSUE THREAD

**Issue by drlove2002** [nextcord/nextcord#1097]
### Summary

When I'm editing tag if a forum thread it's triggering on_thread_update event but there is no different betweet applied_tags of after and before object of thread

### Reproduction Steps

- Create a forum channel
- Create a thread post in the forum
- Add a breakpoint in on_thread_update event
- Observe both after and before object's applied_tags

There is no difference even if I've removed or added a tag.

### Minimal Reproducible Code

```python
    @Cog.listener()
    async def on_thread_update(self, before: Thread, after: Thread):
        if tags := (set(before.applied_tags) - set(after.applied_tags)):
            print("Added", tags.pop())
            return

        if tags := (set(after.applied_tags) - set(before.applied_tags)):
            print("Added", tags.pop())
            return

        print("No tags edited")
```

### Expected Results

There should be a difference between set(after.applied_tags) and set(before.applied_tags) when I add/remove a tag.

### Actual Results

Both after.applied_tags and before.applied_tags are exactly the same even when I've added or removed a tag.

### Intents

2134923

### System Information

- `Python v3.10.6-final`
- `nextcord v2.5.0-final`
- `aiohttp v3.8.5`
- system info: `Linux 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2`

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I wanted to close the thread when "Fixed" tag is added to the forum post thread.

**Comment by teaishealthy** [comment]
tags isn't updated in FormumChannel._update
https://github.com/nextcord/nextcord/blob/master/nextcord/channel.py#L939
