### ISSUE TITLE
@silent message

### ISSUE THREAD

**Issue by MitruMesre** [nextcord/nextcord#1137]
### Summary

add support for silent messages

### What is the feature request for?

Application commands

### The Problem

add support for silent messages

### The Ideal Solution

I think the best way would be
await interaction.response.send_message("Hello World!", silent=True)

### The Current Solution

N/A

**Comment by ooliver1** [comment]
Set `suppress_notifications` via `flags` in `.send()`

**Comment by Soheab** [comment]
> Set `suppress_notifications` via `flags` in `.send()`

Can say the same for `suppress_embeds`. The doc for the  `flags` param needs updating too.
