### ISSUE TITLE
Use global name if nickname is not available

### ISSUE THREAD

**Issue by drlove2002** [nextcord/nextcord#1144]
### Summary

feat(display name): Use global name if nickname is not available

### What is the feature request for?

The core library

### The Problem

The current `Member.display_name` attribute in the library doesn't utilize the `global_name` property when a nickname is not available. This means that the global name is not being displayed as intended. Implementing this feature would allow for a more accurate representation of user names.

### The Ideal Solution

The ideal solution would involve modifying the `display_name` attribute to prioritize the `global_name` property if a nickname is not available. This way, users' global names will be displayed when applicable, providing a more comprehensive representation.

### The Current Solution

The current solution is to use the nickname if available, otherwise, it falls back to using the username. The global_name property is not considered in this process.

### Additional Context

```py
    @property
    def display_name(self) -> str:
        """:class:`str`: Returns the user's display name.

        For regular users this is just their username, but
        if they have a guild specific nickname then that
        is returned instead.
        """
        return self.nick or self.global_name or self.name
        ```

**Comment by lordcod** [comment]
In fact, I was also affected by this problem, as for me it is necessary to put a global name instead of a name, and if it does not exist, then it is already normal
