### ISSUE TITLE
Missing feature for reloading cogs!

### ISSUE THREAD

**Issue by Blxxded** [nextcord/nextcord#1154]
### Summary

Support for extras in reload_extension()

### What is the feature request for?

The core library

### The Problem

Error `reload_extension() got an unexpected keyword argument 'extras'` appears when reloading a cog doing:
```py
bot.reload_extension("cogs.me_cog", extras={"keyword_arg": True})
```
Error `_init__() missing 1 required positional argument: 'keyword_arg'` happens when reloading the cog without providing the extras argument:
```py
bot.reload_extension("cogs.me_cog")
```

### The Ideal Solution

The ideal solution would be adding support for extras in the `reload_extension()` function, an example would be:
```py
bot.reload_extension("cogs.me_cog", extras={"keyword_arg": True})
```

### The Current Solution

The current solution provided after opening a support ticket through [Nextcord's Official Discord Server](https://discord.gg/nextcord) was doing:
```py
bot.unload_extension("cogs.me_cog")
bot.load_extension("cogs.me_cog", extras={"keyword_arg": True})
```

**Comment by Jodenee** [comment]
I'll see if I can add this.
