### ISSUE TITLE
DeprecationWarning: 'audioop' is deprecated and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by lucasadsouza** [nextcord/nextcord#1174]
### Summary

'audioop' is deprecated and slated for removal in Python 3.13

### Reproduction Steps
Run pytest on a nextcord Bot.

### Minimal Reproducible Code

```python
There is no need for a reproducible code, audioop was added to the deprecated modules list since Python 3.11:
https://peps.python.org/pep-0594/#deprecated-modules
```

### Expected Results

No warnings.

### Actual Results

=================================== warnings summary ===================================
Lib\site-packages\nextcord\player.py:5
  C:\Users\username\OneDrive\Documents\Sync\Dev\venvname\Lib\site-packages\nextcord\player.py:5: DeprecationWarning: 'audioop' is deprecated and slated for removal in Python 3.13
    import audioop

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

### Intents

nextcord.Intents.all()

### System Information

- Python v3.11.8-final
- nextcord v2.6.0-final
- aiohttp v3.9.1
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Not something urgent since it is for 3.13, but I thought it would be nice to inform since there is not a suggestion for replacement in PEP 594.

Thank you.

**Comment by EmreTech** [comment]
I wouldn't say this is a bug and instead more of a feature request, but thanks anyways!
