### ISSUE TITLE
Change event system to use only a single parameter for all events.

### ISSUE THREAD

**Issue by sairam4123** [nextcord/nextcord#119]
### Summary

Change event system to use only a single parameter for all events. Potentially only in the core library since discord.ext.commands would be in a weird spot.

### What is the feature request for?

The core library

### The Problem

The event system has different parameters for different events, this seems pretty inconsistent.

### The Ideal Solution

Change event system to use only a single parameter for all events. This will make the event system feel consistent across different events.

### Additional Context

Ported over from [v2.0](https://github.com/Rapptz/discord.py/projects/3#card-58336471) discord.py project.

**Comment by sairam4123** [comment]
This was one of the planned features, so I'm really hoping for this.

**Comment by veni-vidi-code** [comment]
Would be quite breaking thou

**Comment by MoonlightCapital** [comment]
What would this be replaced with?

**Comment by sairam4123** [comment]
A single parameter, just like Hikari.

**Comment by TAG-Epic** [comment]
What about checking if the listener accepts two parameters and throwing a warning..? Would get people to move to one parameter while allowing legacy code to still work.

And then maybe change to one param only once all the major forks make it mandatory with one?

**Comment by ooliver1** [comment]
:thonk: I thought we wanted minimal breaking changes

**Comment by Skelmis** [comment]
I'm curious about this though, its just abstracted what was previously x params into one and adding an extra `.` lookup in order to gain access to the variables?

**Comment by sairam4123** [comment]
I guess, I'd recommend looking how Hikari does it.

**Comment by ooliver1** [comment]
it just makes more sense not having a billion event objects and having to use `.` for everything

**Comment by vcokltfre** [comment]
If we do choose to do it like this, that's probably a change best suited to V3 because that's a massively breaking change

**Comment by TAG-Epic** [comment]
> If we do choose to do it like this, that's probably a change best suited to V3 because that's a massively breaking change

Possibly, although this is still v2 alpha so we can fit in it v2

**Comment by vcokltfre** [comment]
It's also just a huge amount of work to put in just for it to be redone anyway with v3

**Comment by Skelmis** [comment]
> it just makes more sense not having a billion event objects and having to use `.` for everything

This is precisely what I mean. It's just extra overhead hidden behind the guise of making all events only take 1 parameter instead of specific parameters
