### ISSUE TITLE
Redesigning HelpCommand and changing the DefaultHelpCommand.

### ISSUE THREAD

**Issue by sairam4123** [nextcord/nextcord#120]
### Summary

Redesigning HelpCommand and changing the DefaultHelpCommand.

### What is the feature request for?

The core library

### The Problem

Currently, the help command from nextcord feels a lot outdated, the overall design feels bad.

### The Ideal Solution

The default help command should be atleast easily tweakable and should be par with the new Bot's Help commands while still having the option to add commands dynamically (who likes to add commands manually lol.)

### The Current Solution

Currently, we have to create a help command ourselves, most people choose static help commands, but in my opinion, a good looking Dynamic Help command is the best to go.

### Additional Context

Ported over from [v2.0 discord.py project](https://github.com/Rapptz/discord.py/projects/3#card-62697760)

**Comment by parker02311** [comment]
I will start looking into this

**Comment by ooliver1** [comment]
as bots transition to being mainly slash, i dont see much point in this
