### ISSUE TITLE
Upgrade the minimum Python version

### ISSUE THREAD

**Issue by Skelmis** [nextcord/nextcord#1205]
As we move to `3.0` we have the opportunity to introduce breaking changes, as a part of this I would like to propose a discussion surrounding moving the supported Python versions from it's current state to `Python 3.12` which is the version currently in bugfix ([source](https://devguide.python.org/versions/)).

**Comment by alentoghostflame** [comment]
I would be cool with that, especially since the latest LTS release of Ubuntu uses 3.12

**Comment by EmmmaTech** [comment]
I think 3.12 is a bit too cutting edge, 3.10 sounds more reasonable for me. although, I would love an excuse to use the new type variable syntax in 3.12...

**Comment by ooliver1** [comment]
> I would be cool with that, especially since the latest LTS release of Ubuntu uses 3.12

I support this idea too, 2.0 was released with 3.8 minimum when that was about as new as 3.8 is now.
