### ISSUE TITLE
A built-in help command that includes pagination by default

### ISSUE THREAD

**Issue by sairam4123** [nextcord/nextcord#121]
### Summary

A built-in help command that includes pagination by default

### What is the feature request for?

The core library

### The Problem

The problem is we have to create our own pagination for commands by overriding some methods.

### The Ideal Solution

The ideal solution is to implement paginated help command that focuses on customisability (maybe).

### Additional Context

Ported over from [2.0 discord.py project](https://github.com/Rapptz/discord.py/projects/3#card-62697760)

**Comment by ooliver1** [comment]
dupe of #120 ?
