### ISSUE TITLE
Add support for Python 3.13

### ISSUE THREAD

**Issue by LevBernstein** [nextcord/nextcord#1222]
### Summary

Nextcord is currently unusable on Python 3.13 due to a number of breaking changes. We should add support for 3.13

### What is the feature request for?

The core library

### The Problem

Due to the deprecation of audioop (https://github.com/nextcord/nextcord/issues/1174) and an issue with building docs (https://github.com/nextcord/nextcord/issues/1220), nextcord is not currently usable on Python 3.13, whether being run as a user of the library or as someone trying to build the development version locally.

### The Ideal Solution

Merging the following two PRs should add support for Python 3.13:
https://github.com/nextcord/nextcord/pull/1218
https://github.com/nextcord/nextcord/pull/1221
In addition, for the sake of future proofing, I would suggest merging in this PR as well:
https://github.com/nextcord/nextcord/pull/1219

There could be other issues I have not yet encountered, but running my own bot locally with those fixes, everything works just fine on 3.13.

**Comment by Skelmis** [comment]
I believe this issue is now resolved with the merge of the relevant PR's.
