### ISSUE TITLE
Bot.dispatch causing error

### ISSUE THREAD

**Issue by shahriyardx** [nextcord/nextcord#160]
### Summary

It does not work before the bot is ready

### Reproduction Steps

- Create a commands.Bot instance
- call dispatch before on_ready is dispatched

### Minimal Reproducible Code

```python
from nextcord.ext import commands

bot = commands.Bot(command_prefix='?')

@bot.event
async def on_something():
    print('Something happened')

bot.dispatch('something')

bot.run("TOKEN")
```

### Expected Results

No error

### Actual Results

```sh
Traceback (most recent call last):
  File "C:\Users\conta\AppData\Local\Programs\Python\Python39\lib\site-packages\nextcord\ext\ipc\server.py", line 77, in start      
    self.bot.dispatch("soemthing_ready")
  File "C:\Users\conta\AppData\Local\Programs\Python\Python39\lib\site-packages\nextcord\ext\commands\bot.py", line 155, in dispatch
    super().dispatch(event_name, *args, **kwargs)  # type: ignore
  File "C:\Users\conta\AppData\Local\Programs\Python\Python39\lib\site-packages\nextcord\client.py", line 403, in dispatch
    self._schedule_event(coro, method, *args, **kwargs)
  File "C:\Users\conta\AppData\Local\Programs\Python\Python39\lib\site-packages\nextcord\client.py", line 363, in _schedule_event   
    return asyncio.create_task(wrapped, name=f'nextcord: {event_name}')
  File "C:\Users\conta\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 360, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'Client._run_event' was never awaited
```

### Intents

None

### System Information

- Python v3.9.6-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a2
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The dispatch method seems to work fine after the bot's on ready is dispatched. But not before. While in discord.py it worked without any issues

Working code

```py
from nextcord.ext import commands

bot = commands.Bot(command_prefix='?')

@bot.event
async def on_ready():
    print('Bot ready')
    bot.dispatch('something')

@bot.event
async def on_something():
    print('Something happened')

bot.run("TOKEN")
```

**Comment by ooliver1** [comment]
Dispatching event before it's all ready, that wouldn't work because no event listeners/events will be registered

**Comment by shahriyardx** [comment]
Last version I remember is 1.7.3 and it works in 1.7.3, we can dispatch any event before bot is ready. But now its confirmed that it wont work I will have to fix the codes I guess. Thanks.
