### ISSUE TITLE
Student Hubs

### ISSUE THREAD

**Issue by veni-vidi-code** [nextcord/nextcord#164]
### Summary

Adding Student Hubs Channel

### What is the feature request for?

The core library

### The Problem

Currently student hubs are not included in the libary, but are already available. this might result in errors regarding invites trying to be resolved (bots can not join so far but invites might throw errors)

### The Ideal Solution

Implement a basic placeholder for them without any major functions

### The Current Solution

none

### Additional Context

https://github.com/discord/discord-api-docs/pull/3757

**Comment by RenatoLopes771** [comment]
> Currently student hubs are not included in the libary, but are already available. this might result in errors regarding invites trying to be resolved (bots can not join so far but invites might throw errors)

I do not understand this. You want bots to be able to join student hubs? I'm not sure it's possible, or even allowed (because you need a student email to join). Student hubs also don't have any text channels to themselves, they simply show a list of servers that some students from the hub are owners of.

That doesn't stop a bot from interacting with a server that is part of the hub though, since in the end that's just a normal server.

**Comment by TAG-Epic** [comment]
No, as shown in the additional context, a new guild feature and a new channel type was added for students hub

**Comment by veni-vidi-code** [comment]
> > Currently student hubs are not included in the libary, but are already available. this might result in errors regarding invites trying to be resolved (bots can not join so far but invites might throw errors)
> 
> I do not understand this. You want bots to be able to join student hubs? I'm not sure it's possible, or even allowed (because you need a student email to join). Student hubs also don't have any text channels to themselves, they simply show a list of servers that some students from the hub are owners of.
> 
> That doesn't stop a bot from interacting with a server that is part of the hub though, since in the end that's just a normal server.

i do not want them to be able to join, but be able to understand the invites as invites to student hubs and display them correspondingly

**Comment by ooliver1** [comment]
for ref for if this is ever  merged ddocs' side https://github.com/discord/discord-api-docs/pull/4701
