### ISSUE TITLE
guild.create_sticker() raises HTTPException 400 when description is None or ""

### ISSUE THREAD

**Issue by HexCodeFFF** [nextcord/nextcord#165]
### Summary

guild.create_sticker() raises HTTPException 400 when description is None or ""

### Reproduction Steps

1. use `guild.create_sticker()` without specifying the description argument or specify it as `None` or `""`.

### Minimal Reproducible Code

```python
from nextcord.ext import commands
bot = commands.Bot(command_prefix="!")
@bot.command()
async def add_sticker(ctx):
    attachment = await ctx.message.attachments[0].to_file()
    await ctx.guild.create_sticker(name="sticker", emoji="👍", file=attachment)
bot.run("your_token")

then add the bot to a server with stickers and send the command `!add_sticker` with an attachment
```

### Expected Results

the sticker should successfully add to the guild.

### Actual Results

the function raises an HTTPException
```
Ignoring exception in command add_sticker:
Traceback (most recent call last):
  File "C:\Users\minec\.virtualenvs\nextcord_bug-bk92j3GZ\lib\site-packages\nextcord\ext\commands\core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\minec\PycharmProjects\nextcord bug\main.py", line 9, in add_sticker
    await ctx.guild.create_sticker(name="sticker", emoji="👍", file=attachment)
  File "C:\Users\minec\.virtualenvs\nextcord_bug-bk92j3GZ\lib\site-packages\nextcord\guild.py", line 2231, in create_sticker
    data = await self._state.http.create_guild_sticker(self.id, payload, file, reason)
  File "C:\Users\minec\.virtualenvs\nextcord_bug-bk92j3GZ\lib\site-packages\nextcord\http.py", line 336, in request
    raise HTTPException(response, data)
nextcord.errors.HTTPException: 400 Bad Request (error code: 0): The browser (or proxy) sent a request that this server could not understand.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\minec\.virtualenvs\nextcord_bug-bk92j3GZ\lib\site-packages\nextcord\ext\commands\bot.py", line 995, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\minec\.virtualenvs\nextcord_bug-bk92j3GZ\lib\site-packages\nextcord\ext\commands\core.py", line 895, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\minec\.virtualenvs\nextcord_bug-bk92j3GZ\lib\site-packages\nextcord\ext\commands\core.py", line 177, in wrapped
    raise CommandInvokeError(exc) from exc
nextcord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 0): The browser (or proxy) sent a request that this server could not understand.
```

### Intents

Intents.default (not even using intents kwarg for bot)

### System Information

- Python v3.8.3-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a2
- aiohttp v3.6.3
- system info: Windows 10 10.0.22000

note: you might want to change the command to `python -m nextcord -v` 😜

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I suspect this issue stems from a misunderstanding of [the strange way discord implemented this function.](https://discord.com/developers/docs/resources/sticker#create-guild-sticker). the description argument is **not optional** in the API request, but it can be empty. it seems the library does not pass the server the description argument if its None or `""`. since the argument is (for some reason) required, discord freaks out and throws an error. i'm not familiar with the inner workings of discord.py myself but i suspect that actually passing the description argument with an empty string when the user specifies None or `""` would fix this.

![image](https://user-images.githubusercontent.com/35177464/132934458-3edd6aaf-f3e0-4e4d-83ec-70954fb3d5f6.png)

![image](https://user-images.githubusercontent.com/35177464/132934436-d766f6a2-4db6-42de-b2f1-e501e1511663.png)

**Comment by shepherdjay** [comment]
I can try taking a stab at this one

**Comment by TAG-Epic** [comment]
Feel free!
