### ISSUE TITLE
[discordpy v2] In discord.Select, options that are defined as "default" are not present in Select.values If the user does not change the selected options

### ISSUE THREAD

**Issue by veni-vidi-code** [nextcord/nextcord#17]
### Link

https://github.com/Rapptz/discord.py/issues/7284

**Comment by ooliver1** [comment]
In that issue they said discord limitation, self.values isn't official I think you can just manually add them to a list. 

Or if self.values does become official then of course that will be added

**Comment by ooliver1** [comment]
default values are returned by discord now
