### ISSUE TITLE
Slash commands

### ISSUE THREAD

**Issue by Cat4eve** [nextcord/nextcord#174]
### Summary

How a slash commands might be implemented in nextcord 2.0 IMHO

### What is the feature request for?

The core library

### The Problem

Actually, the nextcord doesn't have any implementation of slash commands.

### The Ideal Solution

I think that in order slash commands to be easily understood, they might be designed like a default commands.

bot.command exists which we usually use in order to registrate a command with a specific prefix

Example
```python
@bot.command()
async def test(ctx):
    pass
``` 

What I want to suggest is to make an implementation like a combination of aforementioned example and new buttons.

Example
```python
class SlashCommandOptions:
    name: str
    description: str
    type: int
    options: SlashCommandOptions

class SlashCommand(nextcord.SlashCommand):
    base: dict = {'name':'some name', 'description':'some description'} # required
    subcommand_group: dict = {'name':'some name', 'description':'some description'} # not required
    subcommand: dict = {'name':'some name', 'description':'some description'} # not required
    options: SlashCommandOptions
```

### The Current Solution

Actually, slash commands implementation doesn't exist for nextcord, now.

**Comment by VincentRPS** [comment]
I Think This Would Be A Good Way To Do It

**Comment by TAG-Epic** [comment]
This issue doesn't really give more info. How would options look? How would multiple choices work? How would converters work with this? What about checks? Discord already has a way to restrict commands to spesific roles/users per guild although that's limited. Should we convert pre existing checks to slash ones? How would this be done properly... Please describe how you think all this should look like in the public API

Oh yeah also duplicate issue, there's one on the projects board

**Comment by VincentRPS** [comment]
Maybe Slash's Since Needed Only For Bots For Servers 75+ Could Be Just Commands With A lot More Stuff Like Descriptions Fields etc etc In A Separate Type Of Library Like Nextcord[voice] There Could Be Nextcord[slash] But Different To Voice You Would Import Slash Like If It Were Separate As the Logic Would Be Way Different. I Don't Know About The Role Only / commands So I'm Not Gonna Say Anything About That.

**Comment by Cat4eve** [comment]
> This issue doesn't really give more info. How would options look? How would multiple choices work? How would converters work with this? What about checks? Discord already has a way to restrict commands to spesific roles/users per guild although that's limited. Should we convert pre existing checks to slash ones? How would this be done properly... Please describe how you think all this should look like in the public API
> 
> Oh yeah also duplicate issue, there's one on the projects board

That's my fault, the problem is that I'm not fully aware fo the whole funcional related to slash commands, however I just tried to offer a basic concept. Sorry for my poor code. Events, they might be done like buttons, I mean that each slash command might represent a class and each slash command class might have a callback function with interaction argument in it.

**Comment by ooliver1** [comment]
Is this necessary to be an issue really, GitHub discussions exists or just the discord thread

**Comment by ooliver1** [comment]
Also having slash commands class per one is quite bad, cogs won't work properly and you can simply use a decorator (which currently exists) to make a function that is the callback of the interaction and decorate it with the info of the command and checks, just like ext commands

**Comment by Cat4eve** [comment]
> Also having slash commands class per one is quite bad, cogs won't work properly and you can simply use a decorator (which currently exists) to make a function that is the callback of the interaction and decorate it with the info of the command and checks, just like ext commands

Then, what about buttons, where each button represents a class.

**Comment by ooliver1** [comment]
> > Also having slash commands class per one is quite bad, cogs won't work properly and you can simply use a decorator (which currently exists) to make a function that is the callback of the interaction and decorate it with the info of the command and checks, just like ext commands
> 
> 
> 
> Then, what about buttons, where each button represents a class.

Well yes it will represent a class, but like buttons and normal commands, it will have a shortcut decorator 

Also the options won't just be a dictionary like that but will be more user friendly, it's an api wrapper after all
