### ISSUE TITLE
A webhook example

### ISSUE THREAD

**Issue by TAG-Epic** [nextcord/nextcord#176]
### Summary

title

### What is the feature request for?

The documentation

### The Problem

theres no webhook example

### The Ideal Solution

Make a example for using webhooks

**Comment by BashCache** [comment]
Hi, can I work on this? Can I try out with Slack webhook

**Comment by TAG-Epic** [comment]
Feel free to work on it, although this is a discord library so using a discord webhook is kinda required

**Comment by VFXGamer** [comment]
I can do it, but I want more info on how exactly you want it. By that i mean "How to do" it in the readme or a separate file for that or something completely different. And yea once you confirm me how to do it you can assign me this issue.

**Comment by TAG-Epic** [comment]
We have a examples directory, and what I was thinking was basically showing how to create a webhook object using a URL and send a message. Also we don't really do assignments in case someone leaves the project or gets busy, although feel free to send that you are currently working on it.
