### ISSUE TITLE
Incorrect type annotation for FFmpegPCMAudio stderr

### ISSUE THREAD

**Issue by mjmartis** [nextcord/nextcord#190]
### Summary

Incorrect type annotation for FFmpegPCMAudio stderr

### Reproduction Steps

See code snippet

### Minimal Reproducible Code

```python
stderr: BinaryIO = io.BytesIO()
stream: discord.FFMpegOpusAudio = discord.FFMpegOpusAudio('file.mp3', stderr=stderr)
ctx.voice_client.play(stream)
```

### Expected Results

Successful playback

### Actual Results

Error: `Command raised an exception: UnsupportedOperation: fileno`

Stacktrace:
```
"Command raised an exception: UnsupportedOperation: fileno".
Exception ignored in: <function AudioSource.__del__ at 0xffff908063a0>
Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.9/site-packages/nextcord/player.py", line 115, in __del__
    self.cleanup()
  File "PROJECT.py", line 60, in cleanup
    super().cleanup()
  File "/home/USER/.local/lib/python3.9/site-packages/nextcord/player.py", line 211, in cleanup
    self._kill_process()
  File "/home/USER/.local/lib/python3.9/site-packages/nextcord/player.py", line 176, in _kill_process
    proc = self._process
AttributeError: 'FFMpegOpusAudio' object has no attribute '_process'
```

### Intents

Default

### System Information

Ubuntu 21.04
Python 3.9.5

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The constructor for `FFMpegPCMAudio` accepts a `stderr` argument of type `BinaryIO`. However, instances of `BinaryIO` that don't support the `fileno` operation (for example, `io.BytesIO`) cause an error if passed.

**Comment by Dysta** [comment]
See https://github.com/Rapptz/discord.py/issues/5192

**Comment by ooliver1** [comment]
Your stacktrace means you have not installed ffmpeg.
