### ISSUE TITLE
Role icons

### ISSUE THREAD

**Issue by HexCodeFFF** [nextcord/nextcord#191]
### Summary

implement the ability to view and edit role icons

### What is the feature request for?

The core library

### The Problem

Role icons are a ✨ _sparkly new feature_ ✨ that i'd like to be able to manage with a bot.

### The Ideal Solution

Implement them per the API specs. thats it.

https://discord.com/developers/docs/topics/permissions#role-object

https://discord.com/developers/docs/resources/guild#modify-guild-role

### The Current Solution

It might be possible to use the internal http features of the library to do it

**Comment by HexCodeFFF** [comment]
I have no idea the inner workings of the library, BUT i made this function which works inside of a cog!
```py
    def edit_role_icon(self, role: discord.Role, icon: typing.Union[bytes, str, discord.Emoji, None], *,
                       reason: typing.Optional[str] = None):
        payload = {
            'name': role.name,
            'permissions': role.permissions.value,
            'color': role.color.value,
            'hoist': role.hoist,
            'mentionable': role.mentionable,
            'unicode_emoji': None,
            'icon': None
        }
        if isinstance(icon, str):
            payload['unicode_emoji'] = icon
        elif isinstance(icon, bytes):
            payload['icon'] = discord.utils._bytes_to_base64_data(icon)
        r = Route('PATCH', '/guilds/{guild_id}/roles/{role_id}', guild_id=role.guild.id, role_id=role.id)
        return self.bot.http.request(r, json=payload, reason=reason)```
maybe itll help the lbirary devs

**Comment by veni-vidi-code** [comment]
i am going to look into this
