### ISSUE TITLE
RFC system for organisational management

### ISSUE THREAD

**Issue by redcreeper14385** [nextcord/nextcord#2]
### Summary

An RFC system for proposing changes to Nextcord.

### What is the feature request for?

The core library

### The Problem

As of right now the only way to bring up suggestions and changes is to directly submit an issue or discuss in Discord.

### The Ideal Solution

I propose the NEP system (Nextcord Enhancement Proposal). This is very similar to Python's PEPs and Rust's RFCs. These are numbered proposals with detailed information about a planned feature. NEP-000 will explain how NEPs work and NEP-001 (if everything goes to plan) will propose an organisational "council" structure for the project. This will facilitate a system which is far more organised and efficient than that of dpy. Further details will go in NEP-000 (which I intend on drafting should this go through).

### The Current Solution

N/A, this is a new system.

### Additional Context

NEPs will be found in a separate repo.

**Comment by TAG-Epic** [comment]
I do agree with how PEPs and RFCs are made although I think we should simplify it a bit.

Everything doesn't need to be under the spec like how we do management here. NEPs should ideally just be issues with a short summary of what it does, a example of how something using it would look like honestly. We avoid issue spam like in discord.py and we don't waste too much time writing issues.

**Comment by redcreeper14385** [comment]
I suppose, although an organised system would likely be more efficient in the long term. I have no problem with simplifying it to be less formal though.

**Comment by TAG-Epic** [comment]
We should just improve issue templates honestly.

**Comment by redcreeper14385** [comment]
Templates could be the best thing ever and they still wouldn't make a difference to how organised the system is.
You seem significantly opposed to this though, so it doesn't matter.
