### ISSUE TITLE
Test Python 3.10

### ISSUE THREAD

**Issue by veni-vidi-code** [nextcord/nextcord#216]
### Summary

Support for 3.10

### What is the feature request for?

The core library

### The Problem

The hole libary should get tested on 3.10. and possible issues should be resolved. In our current requirments 3.10 is allowed but it is neither documented nor tested

### The Ideal Solution

Test it and document it

**Comment by VincentRPS** [comment]
in my testing and use of 3.10 the last month or 2 it's worked perfectly fine i don't really see an incentive for this to be open anymore.

**Comment by ooliver1** [comment]
Yeah others using it works fine after updating aiohttp
