### ISSUE TITLE
[commands]bot.process_with_str

### ISSUE THREAD

**Issue by veni-vidi-code** [nextcord/nextcord#24]
### Link

https://github.com/Rapptz/discord.py/issues/7067

**Comment by vcokltfre** [comment]
I think this is a very useful idea right now and should be worked on, however, it should be considered that with the transition to Slash commands, it may not be hugely useful going forwards.

**Comment by koala9712** [comment]
It may be useful for bots in less than a hundred guilds, or those bots who do not make the transition to slash and/or get message content intent
