### ISSUE TITLE
Bot randomly eixting stage channel and making it stop

### ISSUE THREAD

**Issue by veni-vidi-code** [nextcord/nextcord#25]
### Link

https://github.com/Rapptz/discord.py/issues/7034

**Comment by ooliver1** [comment]
just saying unless if someone kicked, tested this in the discord server and it did occur

**Comment by ooliver1** [comment]
i can no longer reproduce this issue, been connected for over 2 hours now, `DEBUG` logs are full with the following keepalives to show it is not a lib issue and may have just been a network issue
```ps
DEBUG   17:00:21 16/06/2022   gateway.py:run                         : Keeping shard ID None voice websocket alive with timestamp 1655395221339.
DEBUG   17:00:21 16/06/2022   gateway.py:send_as_json                : Sending voice websocket frame: {'op': 3, 'd': 1655395221339}.
DEBUG   17:00:21 16/06/2022   gateway.py:received_message            : Voice websocket frame received: {'op': 6, 'd': 1655395221339}
```
