### ISSUE TITLE
The default help command ignores command attributes

### ISSUE THREAD

**Issue by Skelmis** [nextcord/nextcord#250]
### Summary

When setting a command description via the decorator, it should be used in places as the command description. I.e the help commands, instead it is ignored

### Reproduction Steps

Use the default help command and don't set a docstring. Use `description=` instead

It won't show a command description

### Minimal Reproducible Code

```python
@bot.command(description="test")
async def t(ctx):
  pass
```

### Expected Results

`t - test` in the help command

### Actual Results

 instead its shown as having no description

### Intents

N/A

### System Information

N/A

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ooliver1** [comment]
help= works for me

**Comment by Gugu7264** [comment]
`description` appears when doing `!help <command>`, like this:
![Capture d’écran 2021-12-29 à 17 10 41](https://user-images.githubusercontent.com/60748483/147681878-afff8547-702e-4d64-baec-2faf15217014.png)

So you should either use `brief=`, which will entirely show in the `!help` command, and only there, or set the `help` attribute in the decorator, which will entirely show up in `!help <command>` and the first line will show up in the `!help`.

(Though after looking at the docs, I had to go through source code to find what was wrong)
