### ISSUE TITLE
Recording and Streaming Video

### ISSUE THREAD

**Issue by VincentRPS** [nextcord/nextcord#253]
### Summary

Being able to record and show videos/streaming a video/mp4

### What is the feature request for?

The core library

### The Problem

I wanna be able to have my bot be able to record a video to mp4 or other formats and be able to stream it to discord

### The Ideal Solution

Possibly using the Voice Recording feature coming soon as a base for recording audio would be the ideal way but as of recording the actual video I wouldn’t know too much.

### Additional Context

I would fully understand if discord’s current api doesn’t allow this and if so I would propose to possibly add YouTube’s video streaming feature once it is stable

**Comment by TAG-Epic** [comment]
Discord has disabled this feature for bots. If this ever gets turned back on please reopen this issue.
