### ISSUE TITLE
Linting CI

### ISSUE THREAD

**Issue by TAG-Epic** [nextcord/nextcord#260]
### Summary

Linting CI

### What is the feature request for?

The core library

### The Problem

There's no linting process/ci

### The Ideal Solution

Use something like black with GH actions

### The Current Solution

Manually run a linter

**Comment by VincentRPS** [comment]
i think i could do this

**Comment by Skelmis** [comment]
Given the current limitations, if I get around to it I may attempt this with darker as at-least a pre-commit which should *slowly* transition everything..

**Comment by ooliver1** [comment]
merged
