### ISSUE TITLE
No custom emojis in Placeholder for Select menues

### ISSUE THREAD

**Issue by mab-mab** [nextcord/nextcord#267]
### Summary

Can't use custom emojis in placegolders

### Reproduction Steps

Create a Select Menu
insert the custom emoji into Placeholder

### Minimal Reproducible Code

```python
emoji = client.get_emoji(911974529784479814)
        print(emoji)
        super().__init__(placeholder=f'Wähle ein Bundesland aus {emoji}', min_values=1, max_values=1, options=options)
```

### Expected Results

show thie custom emoji

### Actual Results

shows the emoji string e.g:
<:Deutschland:911974529784479814>

### Intents

all

### System Information

- Python v3.9.9-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a3
- aiohttp v3.6.3
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Idk whether thats possible but normal emojis work so i guess custom ones should work as well

**Comment by ooliver1** [comment]
this is most likely a discord limitation as nc never renders the emoji string but discord does

**Comment by mab-mab** [comment]
> this is most likely a discord limitation as nc never renders the emoji string but discord does

yeah probably
