### ISSUE TITLE
unsupported operand type(s) for &: 'int' and 'NoneType' when trying to get channel permission overwrites

### ISSUE THREAD

**Issue by ilyamikheevcoder** [nextcord/nextcord#282]
### Summary

unsupported operand type(s) for &: 'int' and 'NoneType' when trying to get channel permission overwrites

### Reproduction Steps

This error occurs every time I try to get permission overwrites (either by using `channel.overwrites` or `channel.overwrites_for(XXX)`). I guess it happens in any channel that has at least one permission overwrite.
```python
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs)
  File "/workspace/main.py", line 177, in voice_channel
    **Permission overwrites:** {len(channel.overwrites)} \n\
  File "/app/.heroku/python/lib/python3.9/site-packages/nextcord/abc.py", line 486, in overwrites
    overwrite = PermissionOverwrite.from_pair(allow, deny)
  File "/app/.heroku/python/lib/python3.9/site-packages/nextcord/permissions.py", line 714, in from_pair
    for key, value in allow:
  File "/app/.heroku/python/lib/python3.9/site-packages/nextcord/flags.py", line 134, in __iter__
    yield (name, self._has_flag(value.flag))
  File "/app/.heroku/python/lib/python3.9/site-packages/nextcord/flags.py", line 137, in _has_flag
    return (self.value & o) == o
TypeError: unsupported operand type(s) for &: 'int' and 'NoneType'
```

### Minimal Reproducible Code

```python
# run in any channel with permission overwrites
@commands.command()
async def test(ctx):
   print(ctx.channel.overwrites)
```

### Expected Results

I get permission overwrites.

### Actual Results

I get an error in library's internals.

### Intents

nextcord.Intents.all()

### System Information

```
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a3
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.17763
```
This error was also encountered at Debian 11 and replit.com's enviroment.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by RunRun5** [comment]
yes

**Comment by ooliver1** [comment]
This was fixed in the GitHub version, please search how to add a package with `poetry` with a GitHub url
