### ISSUE TITLE
Python Version 3.11

### ISSUE THREAD

**Issue by VincentRPS** [nextcord/nextcord#284]
Testing Out 3.11-dev is something i plan on doing, soon
Newest Downloadable Release: https://www.python.org/downloads/release/python-3110a3/

**Comment by vcokltfre** [comment]
I've changed the priority to low since this is a long way from being something that is vital currently. When 3.11 gets nearer release we can up the priority.

**Comment by ooliver1** [comment]
3.11 is far from being a release, open a new issue if nextcord doesnt fully support 3.11

no point adding support for stuff that can
- change at any time
- isnt the full change list
