### ISSUE TITLE
Support custom event ingests

### ISSUE THREAD

**Issue by veni-vidi-code** [nextcord/nextcord#29]
### Link

https://github.com/Rapptz/discord.py/issues/6711

**Comment by TAG-Epic** [comment]
I think this is a cool idea although it needs to be implemented differently. How about `discord.internals.event` and `discord.internals.opcode` decorators?

**Comment by ooliver1** [comment]
this seems kinda out of scope for this library

custom events can be used with `bot.dispatch("event", *args, **kwargs)`
as for whatever that linked one is about, seems too complex for a niche
