### ISSUE TITLE
add example showing how to safely save your token (env vars?)

### ISSUE THREAD

**Issue by TAG-Epic** [nextcord/nextcord#3]

**Comment by redcreeper14385** [comment]
This should be in the docs I think

**Comment by MoonlightCapital** [comment]
Gotcha. Giving myself a 24 hours deadline for this.

**Comment by H4ckerxx44** [comment]
https://pypi.org/project/python-dotenv/ is good for that

**Comment by TAG-Epic** [comment]
> This should be in the docs I think

yeah that aswell




> https://pypi.org/project/python-dotenv/ is good for that

yeah good idea including that

**Comment by veni-vidi-code** [comment]
https://github.com/Rapptz/discord.py/pull/7272
https://github.com/Rapptz/discord.py/issues/2518

**Comment by TAG-Epic** [comment]
> [Rapptz/discord.py#7272](https://github.com/Rapptz/discord.py/pull/7272)
> [Rapptz/discord.py#2518](https://github.com/Rapptz/discord.py/issues/2518)

Ideally you would have a few examples showing you the different ways of storing it securely, not just overriding the previous examples.

**Comment by MoonlightCapital** [comment]
Okay, I've made this:

https://gist.github.com/MoonlightCapital/54a3434190dc287037b0599931e7db1a

Tell me if it's ok and if yes, where to put it in this repo.

**Comment by TAG-Epic** [comment]
Ideally you would make a example showing it, although specifying using terminal commands to set them aswell

**Comment by H4ckerxx44** [comment]
My two cents:
change
```py
bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
```
to
```py
token = os.environ.get('DISCORD_BOT_TOKEN')
bot.run(token)
```
for simplicity

**Comment by TAG-Epic** [comment]
> My two cents:
> change
> 
> ```python
> bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
> ```
> 
> to
> 
> ```python
> token = os.environ.get('DISCORD_BOT_TOKEN')
> bot.run(token)
> ```
> 
> for simplicity

or just changing it to os.environ["DISCORD_BOT_TOKEN"]

**Comment by Aspect1103** [comment]
You could also have a simpler version which uses an external python file which stores the token as a variable. Then in the main bot file, you just import that file and reference the variable.

It would also work with .gitignore as you just ignore that file. For my bot, I call mine 'Config.py'.

**Comment by TAG-Epic** [comment]
Yeah

**Comment by H4ckerxx44** [comment]
#42
