### ISSUE TITLE
Use Slash Commands with Cogs

### ISSUE THREAD

**Issue by MRvillager** [nextcord/nextcord#312]
### Summary

Use Slash Commands with Cogs

### What is the feature request for?

The core library

### The Problem

You can't use slash commands with Cogs.

### The Ideal Solution

I think the optimal solution is to add the option to declare slash commands like a simple command.  

Example:

``` python
from nextcord.ext import commands
from nextcord import Interaction


class Example(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot

    @commands.slash_command(
        name="example",
        description="Cantami, o Diva, del Pelìde Achille l'ira funesta che infiniti addusse lutti agli Achei",
    )
    async def example(self, interaction: Interaction, arg0: int, arg1: int):
        await interaction.response.send_message(f"{arg0} + {arg1} = {arg0 + arg1}")


```

### The Current Solution

The current solution is simply to not use cogs.

**Comment by Soheab** [comment]
You can use `@nextcord.slash_command(...)` for now.

**Comment by VincentRPS** [comment]
@MRvillager commands.slash_command doesn't exist only nextcord.slash_command

**Comment by MRvillager** [comment]
> @MRvillager commands.slash_command doesn't exist only nextcord.slash_command

Yeah, I know. It's a suggestion for the implementation of slash commands inside cogs.

**Comment by TAG-Epic** [comment]
It makes no sense for it to be inside ext.commands.

**Comment by MRvillager** [comment]
It makes sense to me because to declare commands inside cogs you use `@commands.command()`, which is inside `nextcord.ext`. So to maintain consistency with the old commands it should be inside ext.commands.

**Comment by Skelmis** [comment]
As a side note, ``ext`` exists for extensions which are outside of the core discord api. So slash commands, being in the api and not an extension we add for convenience come under just ``nextcord``

**Comment by MRvillager** [comment]
In that case, the solution would be to implement a new Cog class dedicated for slash commands.

**Comment by ooliver1** [comment]
It already exists?

**Comment by ooliver1** [comment]
ClientCog and commands.Cog subclasses it so it works in cogs

**Comment by ooliver1** [comment]
see what soheab said at the start of this thread

**Comment by MRvillager** [comment]
My bad, I just checked it. Given that, I think there should be an example on how to use it, just for completeness.
