### ISSUE TITLE
Client.slash_command fails when annotations future is enabled

### ISSUE THREAD

**Issue by sam-rockett** [nextcord/nextcord#328]
### Summary

Client.slash_command fails when annotations future is enabled

### Reproduction Steps

Produce a basic bot using nextcord.Client, then try to create a slash command with `from __future__ import annotations` enabled.

I have not tested if this is also the case with nextcord.ext.Bot.

### Minimal Reproducible Code

```python
from __future__ import annotations

import nextcord

bot = nextcord.Client()


@bot.slash_command("echo")
async def echo(it, arg: str):
    await it.response.send_message(arg)


if __name__ == '__main__':
    bot.run(TOKEN)
```

### Expected Results

A bot with the command "/echo"

This is the case for if the annotations import is commented out.

### Actual Results

A `NotImplementedError` stating that "str" is not a valid type for an argument. 

Debugger shows that the value for `typing` in `application_command.CommandOption.get_type` is `{str} 'str'`

```
Traceback (most recent call last):
  File "E:\scratch\bugtest.py", line 9, in <module>
    async def test(it, arg: str):
  File "E:\venv\lib\site-packages\nextcord\client.py", line 1972, in decorator
    result = slash_command(name=name, description=description, guild_ids=guild_ids,
  File "E:\venv\lib\site-packages\nextcord\application_command.py", line 1232, in decorator
    app_cmd = ApplicationCommand(
  File "E:\venv\lib\site-packages\nextcord\application_command.py", line 757, in __init__
    super().__init__(callback=callback, cmd_type=cmd_type, name=name, description=description)
  File "E:\venv\lib\site-packages\nextcord\application_command.py", line 387, in __init__
    self._from_callback(callback)
  File "E:\venv\lib\site-packages\nextcord\application_command.py", line 465, in _from_callback
    arg = CommandOption(value)
  File "E:\venv\lib\site-packages\nextcord\application_command.py", line 224, in __init__
    self.type: ApplicationCommandOptionType = self.get_type(parameter.annotation)
  File "E:\venv\lib\site-packages\nextcord\application_command.py", line 263, in get_type
    raise NotImplementedError(f'Type "{typing}" isn\'t a supported typing for Application Commands.')
NotImplementedError: Type "str" isn't a supported typing for Application Commands.
```

### Intents

None

### System Information

- Python v3.10.0-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a5
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The annotations future implicitly makes all type hints on the file it uses into forward references (essentially casting to string) in order to allow for type hints that reference things that have not been imported yet (useful for resolving circular imports) or are only partially constructed (e.g. annotating the class name during the definition of the class.)

According to [PEP-563][PEP-563], code using annotations should be using `typing.get_type_hints()` to correctly resolve type hints at runtime (as passing strings into type hints is already valid without the future import anyway.)

[PEP-563]: https://www.python.org/dev/peps/pep-0563/#resolving-type-hints-at-runtime

**Comment by vcokltfre** [comment]
Wontfix, we've decided that this is not worth fixing right now as it requires a large change to the internals of the library, which is best suited to V3
