### ISSUE TITLE
Fetching a member in slash doesn't give a banner

### ISSUE THREAD

**Issue by techpluscraft** [nextcord/nextcord#329]
### Summary

When you do await interaction.guild.fetch_member(member.id) it doesn't return the member banner

### Reproduction Steps

Do 
```py
await interaction.guild.fetch_member(member.id)
```
in your code

### Minimal Reproducible Code

```python
await interaction.guild.fetch_member(member.id)
```

### Expected Results

The banner url

### Actual Results

None

### Intents

Default

### System Information

```
- Python v3.8.12-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a5
- aiohttp v3.6.3
- system info: Linux 5.11.0-1023-gcp #25~20.04.1-Ubuntu SMP Mon Nov 15 15:54:39 UTC 2021
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by ooliver1** [comment]
Correct me if I'm wrong but I remember that discord for some reason doesn't send banners when fetching member but only fetching user

**Comment by techpluscraft** [comment]
> Correct me if I'm wrong but I remember that discord for some reason doesn't send banners when fetching member but only fetching user

Your probably right, hopefully they fix it

**Comment by vcokltfre** [comment]
I've tested this and it is an API limitation, I'll mark this as invalid for now, but if the API resolves this in the near future please re-open this.
