### ISSUE TITLE
Slash and normal cogs dont load together

### ISSUE THREAD

**Issue by ZaneRE544** [nextcord/nextcord#333]
### Summary

I made a prefixed cog and a slash cog but I get an 'already loaded' error

### Reproduction Steps

1. I made a prefixed command and put it in a cog folder
2. I made the same command but in slash command and put it in a different folder
3. Clicked on debug to see if they will load together

### Minimal Reproducible Code

```python

# from main.py
bot.load_extension('cog.fun')
bot.load_extension('slashcog.slashfun')

# from the fun.py cog
@jeanne(aliases=['8ball', '8b']) #prefixed and put in a cog folder (example)
    @cooldown(1, 5, BucketType.user)
    async def _8ball(self, ctx, *, question=None):
        if not question:
            noquestion = Embed(
                description="Please add a question")
            await ctx.send(embed=noquestion)
        else:
            embed = Embed(color=0x0000FF)
            embed.add_field(name="Question:", value=f'{question}', inline=False)
            embed.add_field(
                name="Answer:", value=f'{choice(eight_ball_answers)}', inline=False)
            await ctx.send(embed=embed)

# from the slashfun.py
    @jeanne_slash(name='8ball', description="Ask 8 ball anything and you will get your awnser") #slash command put in a different folder (example)
    async def _8ball(self, interaction: Interaction, question):
        embed = Embed(color=0x0000FF)
        embed.add_field(name="Question:", value=f'{question}', inline=False)
        embed.add_field(
            name="Answer:", value=f'{choice(eight_ball_answers)}', inline=False)
        await interaction.response.send_message(embed=embed)
```

### Expected Results

Both cogs load together, no problems

### Actual Results

"Already loaded" error and they are in different folders

### Intents

Default

### System Information

- Python v3.10.1-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a5
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by koala9712** [comment]
Unable to reproduce, Might be a problem with `jeanne`?

System Information:
- Python 3.8.10
- Nextcord 2.0.0a5
- aiohttp v3.8.1
- Windows 10

File structure:
```
Project:
    cogs:
        slashcmd.py
        regularcmd.py
    main.py
```   
Code Used:
```python
# slashcmd.py
import nextcord
from nextcord.ext import commands

class slashcmd(commands.Cog):
    def __init__(self, bot) -> None:
        self.bot = bot

    @nextcord.slash_command(name="mute", guild_ids=[0])
    async def cmdcmd(self, interaction: nextcord.Interaction):
        await interaction.send("no")

def setup(bot):
    bot.add_cog(slashcmd(bot))
```
```python
# regularcmd.py
from nextcord.ext import commands

class regularcmd(commands.Cog):
    def __init__(self, bot) -> None:
        self.bot = bot

    @commands.command()
    async def cmdcmd(self, ctx):
        await ctx.send("no")

def setup(bot):
    bot.add_cog(regularcmd(bot))
```
```python
# main.py
import asyncio

from nextcord.ext import commands
import nextcord


bot = commands.Bot(
    command_prefix="!!",
    intents=nextcord.Intents.all(),
    )

@bot.event
async def on_ready():
    print(f"Logged in.")

async def my_startup_function():
    bot.load_extension("cogs.slashcmd")
    bot.load_extension("cogs.regularcmd")
    await bot.start("token")

asyncio.run(my_startup_function())

```

**Comment by ZaneRE544** [comment]
> Unable to reproduce, Might be a problem with `jeanne`?
> 
> System Information:
> 
> * Python 3.8.10
> * Nextcord 2.0.0a5
> * aiohttp v3.8.1
> * Windows 10
> 
> File structure:
> 
> ```
> Project:
>     cogs:
>         slashcmd.py
>         regularcmd.py
>     main.py
> ```
> 
> Code Used:
> 
> ```python
> # slashcmd.py
> import nextcord
> from nextcord.ext import commands
> 
> class slashcmd(commands.Cog):
>     def __init__(self, bot) -> None:
>         self.bot = bot
> 
>     @nextcord.slash_command(name="mute", guild_ids=[0])
>     async def cmdcmd(self, interaction: nextcord.Interaction):
>         await interaction.send("no")
> 
> def setup(bot):
>     bot.add_cog(slashcmd(bot))
> ```
> 
> ```python
> # regularcmd.py
> from nextcord.ext import commands
> 
> class regularcmd(commands.Cog):
>     def __init__(self, bot) -> None:
>         self.bot = bot
> 
>     @commands.command()
>     async def cmdcmd(self, ctx):
>         await ctx.send("no")
> 
> def setup(bot):
>     bot.add_cog(regularcmd(bot))
> ```
> 
> ```python
> # main.py
> import asyncio
> 
> from nextcord.ext import commands
> import nextcord
> 
> 
> bot = commands.Bot(
>     command_prefix="!!",
>     intents=nextcord.Intents.all(),
>     )
> 
> @bot.event
> async def on_ready():
>     print(f"Logged in.")
> 
> async def my_startup_function():
>     bot.load_extension("cogs.slashcmd")
>     bot.load_extension("cogs.regularcmd")
>     await bot.start("token")
> 
> asyncio.run(my_startup_function())
> ```

i did `from nextcord.ext.command import commands as jeanne`

**Comment by ZaneRE544** [comment]
ok i found a solution. where it said in the class line, i had to give it a different name like `class fun(Cog)` for prefixed but `class slashfun(Cog)` for slash and just loaded perfectly
