### ISSUE TITLE
Small mistype in the docs.

### ISSUE THREAD

**Issue by Shlol762** [nextcord/nextcord#339]
This [small error](https://github.com/nextcord/nextcord/blob/2df2c62cbf929352e106e12cdb0c4c53f605ae04/nextcord/ext/commands/core.py#L281) shows on the docs, and people might end up missing the ```inherit_hooks``` parameter to pass in to `Command`. Although I'm not sure if it's supposed to be ```inherit_hooks``` or ```inherit_checks```. Ths issue is visible in the docs under attr [`extras`](https://nextcord.readthedocs.io/en/latest/ext/commands/api.html#nextcord.ext.commands.Command.extras).

**Comment by Skelmis** [comment]
Great catch!

I'll take a look into fixing that
