### ISSUE TITLE
Alias does not export same values

### ISSUE THREAD

**Issue by onerandomusername** [nextcord/nextcord#359]
### Summary

alias doesn't export all of the same objects

### Reproduction Steps

ran a custom script that imports all of the packages in namespace nextcord and checks them against all objects in namespace discord 

### Minimal Reproducible Code

```python
>>> from nextcord.ext import tasks as n_tasks
>>> from discord.ext import tasks as d_tasks
>>> print(n_tasks.Loop is d_tasks.Loop)
```

### Expected Results

True

### Actual Results

False

### Intents

---

### System Information

not sure, don't still have the venv

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Full list:
```prolog
Attribute mismatch:  nextcord.interactions.InvalidArgument
Attribute mismatch:  nextcord.interactions.WebhookMessage
Attribute mismatch:  nextcord.ext.commands.InvalidSetupArguments
Attribute mismatch:  nextcord.ext.commands.ScheduledEventConverter
Attribute mismatch:  nextcord.ext.commands.ScheduledEventNotFound
Attribute mismatch:  nextcord.ext.tasks.ET
Attribute mismatch:  nextcord.ext.tasks.FT
Attribute mismatch:  nextcord.ext.tasks.LF
Attribute mismatch:  nextcord.ext.tasks.Loop
Attribute mismatch:  nextcord.ext.tasks.SleepHandle
Attribute mismatch:  nextcord.ext.tasks.T
Attribute mismatch:  nextcord.ext.tasks.loop
```

**Comment by MaskDuck** [comment]
do you have any other library have discord as their namespace

**Comment by ooliver1** [comment]
I can reproduce, it seems to only be caused by `*cord.ext.tasks`, possibly from the structure where everything is defined in the `__init__.py`.

**Comment by ooliver1** [comment]
#1095
