### ISSUE TITLE
Add Migrating to v2.0 and migrating to nextcord

### ISSUE THREAD

**Issue by veni-vidi-code** [nextcord/nextcord#36]
### Summary

Improvment for the docs

### What is the feature request for?

The documentation

### The Problem

There should be a guide on how to port projects over

### The Ideal Solution

Something simular to Migrating to v1.0 in the current docs

**Comment by veni-vidi-code** [comment]
I would assign myself to that if no one else wants to do it

**Comment by redcreeper14385** [comment]
If you do the 2.0 migration guide then I'm happy to look into making a Nextcord migration guide.

**Comment by TAG-Epic** [comment]
Alright I'm gonna assign both of you. Good luck!

**Comment by veni-vidi-code** [comment]
> If you do the 2.0 migration guide then I'm happy to look into making a Nextcord migration guide.

I am going to do a quick setup for both and then we can start writing?

**Comment by redcreeper14385** [comment]
> > If you do the 2.0 migration guide then I'm happy to look into making a Nextcord migration guide.
> 
> I am going to do a quick setup for both and then we can start writing?

That works 🙂

**Comment by ooliver1** [comment]
^^ I did the migrating to 2.0 yesterday

**Comment by veni-vidi-code** [comment]
> ^^ I did the migrating to 2.0 yesterday

thanks. i had to take a break for work

**Comment by ooliver1** [comment]
Isn't this like done?
