### ISSUE TITLE
message.guild is None in message_command

### ISSUE THREAD

**Issue by Gugu7264** [nextcord/nextcord#367]
### Summary

message.guild is None in message_command

### Reproduction Steps

1. Create a message command
2. Make it log/print message.guild
3. --> It's None

### Minimal Reproducible Code

```python
@message_command(name="Test command", guild_ids=[...])
async def test_command(
  self, interaction: nextcord.Interaction, message: nextcord.Message
):
    print(message.guild, interaction.guild) # Prints None, Guild object
    await interaction.send(
        f"{interaction.user.mention} used the command on {message.jump_url}."
    )
```

### Expected Results

message.guild should be provided

### Actual Results

message.guild is None ; message.jump_url is incorrect

### Intents

Intents(                 bans=True,                 guilds=True,                 members=True,                 messages=True,                 presences=False,                 voice_states=True,             )

### System Information

- Python v3.8.12-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a6
- aiohttp v3.7.4.post0
- system info: Linux 4.15.0-122-generic # 124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ooliver1** [comment]
seems to have been indirectly fixed by #530
