### ISSUE TITLE
Global scope of application command guild ids

### ISSUE THREAD

**Issue by ghost** [nextcord/nextcord#395]
### Summary

Something to make itso that you dont have to put guild_ids in every slash command

### What is the feature request for?

The core library

### The Problem

So on each slash command, if you don't want to wait 1 hour for the command to finally update on your testing server, you have to put guild_ids on every command
but it gets annoying something and I have a bad memory
I could forget

### The Ideal Solution

Something that you could put in nextcord.Client() or a function in wich u put ur guild id

### The Current Solution

guild_ids :/

### Additional Context

The ideal solution doesnt have to be what I proposed, but still, it would be those 2 solutions that I think are ideal

**Comment by ooliver1** [comment]
in future, please use descriptive issue titles
