### ISSUE TITLE
Add .jump_url attribute to Messageable

### ISSUE THREAD

**Issue by frissyn** [nextcord/nextcord#396]
### Summary

Add the `.jump_url` property to the `Messageable` mixin class

### What is the feature request for?

The core library

### The Problem

You currently have to manually format a Discord URL to jump to a channel, thread, DM, etc. By adding a `.jump_url` to the `Messageable` mixin, this functionality would be added to those classes.

### The Ideal Solution

`Message`s have a `.jump_url` property that formats a URL string for the client to jump to the message directly. The same implementation that creates the URL could be added to `Messageable`s so that functionality could be provided to channels, DMs, threads, etc.

### Additional Context

As discussed (briefly) in the [#general](https://discord.com/channels/881118111967883295/881118112492191796/936677692626059284) channel of the Nextcord Server.

**Comment by Gugu7264** [comment]
You can mention the channel though?
