### ISSUE TITLE
Slash Command Event

### ISSUE THREAD

**Issue by ElijahGives** [nextcord/nextcord#404]
### Summary

To add an event that is dispatched when  a slash command is used.

### What is the feature request for?

The core library

### The Problem

There's not a big problem I don't think, because right now we have on_interaction which you can filter to get slash commands from.
It will become easier if that event is added because we won't need to filter to get slash commands only, and we can use it for logging too.

### The Ideal Solution

I think the ideal solution is to create an `on_slash_command` event which gets fired when a slash command is used.
I think it should send an `Interaction` to the event  when fired. 

### The Current Solution

Using on_interaction and filtering to get slash commands only.

**Comment by aticie** [comment]
+1 Also the `on_interaction_error` and `on_slash_command_error` would be very useful.

**Comment by Gugu7264** [comment]
I don't think it is needed to have unnecessary events, you can just check against the type to filter whatever command you want to log.

**Comment by ooliver1** [comment]
on_interaction exists for the pure reason that discord sends that event, I don't think we need extra sub events that aren't in the api
