### ISSUE TITLE
Non-descriptive error in Slash when forgetting self

### ISSUE THREAD

**Issue by alentoghostflame** [nextcord/nextcord#420]
### Summary

Making a slash command in a cog and forgetting to put the "self" argument in the command description results in a ~~strange error.~~ better error since #530, but still isn't the greatest.

### What is the feature request for?

The core library

### The Problem

Making a slash command in a cog and forgetting to put the "self" argument in the command description results in a strange error. While erroring out is correct behavior, the error that it provides should be a bit better.

### The Ideal Solution

Find a way, preferably before runtime, to figure out if `self` is possibly missing and raise an error if it is missing.

**Comment by ooliver1** [comment]
the error seems to have improved since #530 and the error now is a reasonable
`TypeError: Cog.command() takes 1 positional argument but 2 were given`
this can be improved but is much better than what i remember the original error to be

**Comment by EmreTech** [comment]
What do you mean by "command's description"?

**Comment by ooliver1** [comment]
i think they mean declaration, like the function definition

**Comment by EmreTech** [comment]
> i think they mean declaration, like the function definition

Ah okay
