### ISSUE TITLE
send_message() got an unexpected keyword argument 'delete_after'

### ISSUE THREAD

**Issue by AnimusXCASH** [nextcord/nextcord#424]
### Summary

Delete after unexpected keyword argument however according to the docs it should be allowed

### Reproduction Steps

await interaction.response.send_message(embed=message_embed, ephemeral=True,delete_after = 2)
TypeError: send_message() got an unexpected keyword argument 'delete_after'

### Expected Results

Custom time on how long interaction response is on channel

### Actual Results

Error 

### Intents

All

### System Information

- Python v3.9.6-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a6
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by TAG-Epic** [comment]
Sorry, the docs are using the development version. Please install from master if you wish to use this param
