### ISSUE TITLE
Implement remove_view in Client

### ISSUE THREAD

**Issue by tasuren** [nextcord/nextcord#425]
### Summary

Implement remove_view that reverse of add_view in Client.

### What is the feature request for?

The core library

### The Problem

Client class has method `add_view`.
This is useful, but if you do it in the constructor of the extension's cog, it will cause a memory leak unless you delete the registered view when the extension is reloaded.
However, `remove_view`, which is the opposite of `add_view` to remove a view, is not implemented.
This is very inconvenient.
Not only does this cause a memory leak, but if you pass an instance of the cog when instantiating the view, the old instance will remain and will be used.
This means that the old version of the cog will be used in the View.
So I thought it would be good to have `remove_view`.

### The Ideal Solution

Example on cog
```python
class ExampleCog(commands.Cog):
  def __init__(self, bot):
    self.view = MyView()
    bot.add_view(self.view)

  def cog_unload(self):
    bot.remove_view(self.view)
```

### The Current Solution

It's a little aggressive, but that's how I'm dealing with it now.
```python
# Remove view added
for key, value in list(bot._connection._view_store._views.items()):
  if key[2] == "CustomID on the view":
    del bot._connection._view_store._views[key]
```

**Comment by TAG-Epic** [comment]
Seems like View.stop also does not remove it from the View store?

**Comment by tasuren** [comment]
I tried it in my environment and it is not working.

```python
print(bot.persistent_views)
# [<ClickCaptchaView timeout=None children=1>, <RolePanelView timeout=None children=3>, <MenuView timeout=None children=4>, <View timeout=None children=1>, <WarnButtonFunp timeout=None children=1>, <CloseButton timeout=None children=1>]

bot.persistent_views[0].stop()

print(bot.persistent_views)
# [<ClickCaptchaView timeout=None children=1>, <RolePanelView timeout=None children=3>, <MenuView timeout=None children=4>, <View timeout=None children=1>, <WarnButtonFunp timeout=None children=1>, <CloseButton timeout=None children=1>]
```

**Comment by Edible223** [comment]
```
class HelpView(nextcord.ui.View):
    def __init__(self, help_command: "MyHelpCommand", options: list[nextcord.SelectOption], *, timeout: Optional[float] = 120.0):
        super().__init__(timeout=timeout)
        self.add_item(HelpDropdown(help_command, options))
        self._help_command = help_command

    async def on_timeout(self):
        # remove dropdown from message on timeout
        self.clear_items()
        await self._help_command.response.edit(view=self)

    async def interaction_check(self, interaction: nextcord.Interaction) -> bool:
        return self._help_command.context.author == interaction.user

```
