### ISSUE TITLE
A `@commands.is_owner()` or similar for slash commands

### ISSUE THREAD

**Issue by codeman1o1** [nextcord/nextcord#433]
### Summary

A `@commands.is_owner()` or similar for slash commands

### What is the feature request for?

nextcord.ext.commands

### The Problem

For normal commands, you can do `@commands.is_owner()` or similar, but this doesn't work for slash commands.

### The Ideal Solution

Something like `@slash_commands.is_owner()` or `@slash_commands.has_any_role(...)`

### The Current Solution

Checking through an if statement

### Additional Context

This is completely optional but could be a nice addition:
If the user is e.g. not the owner of the bot/doesn't have the required role(s), the slash command won't show up for that user.
I don't know if this is even possible

**Comment by Soheab** [comment]
See PR #348

**Comment by codeman1o1** [comment]
Thank you
