### ISSUE TITLE
Why the slash command only work for bot and client, but in the cog it is not work

### ISSUE THREAD

**Issue by rexwu1104** [nextcord/nextcord#434]
### Summary

nextcord.slash_command not work

### Reproduction Steps

I copy code from https://github.com/nextcord/nextcord/blob/master/examples/application_commands/cog_example.py
and change TESTING_GUILD_ID to my guild id

### Minimal Reproducible Code

```python
from nextcord import Intents
import nextcord
from nextcord.ext import commands

bot = commands.Bot(command_prefix='t!', intents=Intents.all())

TESTING_GUILD_ID = 723162132082065501  # Replace with your testing guild id

class ApplicationCommandCog(commands.Cog):
    bot: commands.Bot
    def __init__(self, bot: commands.Bot):
        self.bot = bot

    @nextcord.slash_command(guild_ids=[TESTING_GUILD_ID])
    async def my_slash_command(self, interaction: nextcord.Interaction):
        await interaction.response.send_message("This is a slash command in a cog!")

    @nextcord.user_command(guild_ids=[TESTING_GUILD_ID])
    async def my_user_command(self, interaction: nextcord.Interaction, member: nextcord.Member):
        await interaction.response.send_message(f"Hello, {member}!")

    @nextcord.message_command(guild_ids=[TESTING_GUILD_ID])
    async def my_message_command(self, interaction: nextcord.Interaction, message: nextcord.Message):
        await interaction.response.send_message(f"{message}")
        
@bot.event
async def on_ready():
    bot.add_cog(ApplicationCommandCog(bot))
    print(bot.cogs['ApplicationCommandCog'].__cog_commands__)
        
bot.run('TOKEN')
```

### Expected Results

I can use the slash command named 'my_slash_command'

### Actual Results

nothing happened

### Intents

Intents.all()

### System Information

2.0.0a7

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by atharvaupadhyay** [comment]
Listen do `from nextcord import *` this will import everything
and just do `@slash_command`it will work hope it helps @alentoghostflame

**Comment by rexwu1104** [comment]
sorry, I find the problem, I should add the cog before I run the bot
