### ISSUE TITLE
Support for Attatchment Option type in Slash Commands

### ISSUE THREAD

**Issue by DenverCoder1** [nextcord/nextcord#439]
Application Command Attachment Option Type Now Available

![image](https://user-images.githubusercontent.com/20955511/153103313-e225b6c8-a05d-47dc-a3d1-967da4f7975e.png)

Add options with type 11. The resolved attachments will follow the same structure for attachments in other places.

https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-type

**Comment by DenverCoder1** [comment]
Closed by #440

**Comment by veni-vidi-code** [comment]
> _Will be_ closed by #440

next time just write the Closes text into the pr
