### ISSUE TITLE
guild_only for Slash Commands

### ISSUE THREAD

**Issue by SteffoSpieler** [nextcord/nextcord#441]
### Summary

An option to make a slash command guild only - like in the normal commands.

### What is the feature request for?

The core library

### The Problem

When a slash command requires to be run on a guild, there has to be a check in the beginning of the function.
But then the command is still shown in the menu with all commands in a dm.

### The Ideal Solution

Add something like `guild_only=True` or `@nextcord.guild_only()` and register it do every guild the bot is in.

### The Current Solution

Add a check to the beginning of the command and send a message when there's no guild.

**Comment by TAG-Epic** [comment]
This will be implemented once discord releases perms v2.
