### ISSUE TITLE
overwrites_for() should return None if there are no overwrites

### ISSUE THREAD

**Issue by redcreeper14385** [nextcord/nextcord#46]
### Link

Implemented but not merged in Rapptz/discord.py#2119

**Comment by TAG-Epic** [comment]
I honestly see no reason for this change. I also think we should try to delay breaking changes atm

**Comment by redcreeper14385** [comment]
> we should try to delay breaking changes
**we are literally writing 2.0**

**Comment by TAG-Epic** [comment]
Fair

**Comment by TAG-Epic** [comment]
Seems like this has already been done by Danny.

**Comment by redcreeper14385** [comment]
OK 👍
