### ISSUE TITLE
Remove command feature

### ISSUE THREAD

**Issue by kavin-jindal** [nextcord/nextcord#483]
### Summary

implementation of the remove command

### What is the feature request for?

The core library

### The Problem

implentation of the remove command has not been done yet 

### The Ideal Solution

remove a particular registered command

**Comment by MaskDuck** [comment]
sure i can work on this

**Comment by MaskDuck** [comment]
wait it is done wdym hasnt be done yet

**Comment by DenverCoder1** [comment]
You mean like [bot.remove_command](https://nextcord.readthedocs.io/en/latest/ext/commands/api.html#nextcord.ext.commands.Bot.remove_command)?
