### ISSUE TITLE
Embeds have some sort of Invisible Line

### ISSUE THREAD

**Issue by zenabzz** [nextcord/nextcord#484]
### Summary

Any Embed has some sort of invisible line which makes it appear bigger than supposed to

### Reproduction Steps

1. Create any Embed
2. Send it in any channel

### Minimal Reproducible Code

```python
embed = nextcord.Embed(
          
            description = '**[Rules Here](Insert Rules Link)**',
            
            colour = 3447003
            
        )
        
        await ctx.send(embed = embed)
```

### Expected Results

An Embed with a hyper Link Description and appears normally

### Actual Results

An Embed is sent as expected but it has some sort of invisibile line making it lookw weirdly
![image](https://user-images.githubusercontent.com/88695973/154868647-c8d064e0-c45b-4fbb-ac45-292acb304ce4.png)

### Intents

guild_messages, members, guilds, guild_reactions

### System Information

- Python v3.10.2-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a8
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ooliver1** [comment]
This looks a lot like something the library cannot control, this would be a discord bug if it's not intended

**Comment by TAG-Epic** [comment]
Discord bug
