### ISSUE TITLE
Interaction cooldown

### ISSUE THREAD

**Issue by MaskDuck** [nextcord/nextcord#490]
### Summary

Button Interaction Cooldown.

### What is the feature request for?

The core library

### The Problem

I want to limit how much can my users press a button every x.

### The Ideal Solution

There should have something like `commands.BucketType` but for buttons.

**Comment by MouseMoosz** [comment]
> I want to limit how much can my users press a button every x.

Discord already has a built-in cooldown for interactions, if you try to spam it, it will wait a few seconds and then send the interaction so I think this feature isn't worth the work.

**Comment by MaskDuck** [comment]
this isnt what i want, since we can't custom the cooldown.

**Comment by MouseMoosz** [comment]
> this isnt what i want, since we can't custom the cooldown.

That is true, we cannot have custom cooldown. However, we can implement a really hacky check but that would be a mess, so yes it being implemented in the core library would be nice.

**Comment by TAG-Epic** [comment]
This would get implemented in the slash checks PR
