### ISSUE TITLE
Documentation typo?

### ISSUE THREAD

**Issue by EpicBirb** [nextcord/nextcord#492]
I don't know if this is intentional but I'm just going to say it.

[Typo Here](https://nextcord.readthedocs.io/en/stable/ext/commands/api.html?highlight=context#nextcord.ext.commands.Context.voice_client)
This will redirect you to the documentation on `nextcord.ext.commands.Context.voice_client`

Issue here is that it says that it will return `VoiceProtocol`
![image](https://user-images.githubusercontent.com/68750348/155230424-9e80492b-36ce-41ad-9b21-a3d2e391ddfd.png)

I think this kind of misleading because it in one of your examples [here](https://github.com/nextcord/nextcord/blob/master/examples/basic_voice.py), at line 72. `ctx.voice_client` (ctx is `nextcord.ext.commands.Context` -> ["The class of ctx is nextcord.ext.commands.Context"](https://github.com/nextcord/nextcord/discussions/447) ([Click me to redirect to the example](https://github.com/nextcord/nextcord/blob/master/nextcord/ext/commands/context.py#L69)) has another coroutine function named `play`. Object `VoiceProrocol` doesn't have a coroutine function named `play`, only object `ctx.voice_client` aka [`nextcord.VoiceClient`](https://nextcord.readthedocs.io/en/stable/api.html#nextcord.VoiceClient) has that coroutine function.

If this is wrong, you can close the issue and move on I guess.

**Comment by DenverCoder1** [comment]
VoiceClient is a basic implementation of VoiceProtocol.

If you aren't defining your own protocols, ctx.voice_client will be of type VoiceClient and have a play function.

If you are defining your own implementation of VoiceProtocol, it's possible that it could be returned by ctx.voice_client and it might not have play unless you define it.

In the basic voice example, I believe it is assuming you are using the basic VoiceClient implementation
