### ISSUE TITLE
The ability to convert Command to a slash command

### ISSUE THREAD

**Issue by tuna2134** [nextcord/nextcord#499]
### Summary

Cenvert

### What is the feature request for?

nextcord.ext.commands

### The Problem

I want to make the transition as easy as possible.

### The Ideal Solution

What automatically converts it corresponds to that.

**Comment by Skelmis** [comment]
This is unlikely to become a thing, the data provided for each ``Context`` and ``Interaction`` are different so it requires changes regardless.

**Comment by tuna2134** [comment]
Oh…

**Comment by TAG-Epic** [comment]
This will not be covered by nextcord. Maybe you can find a nextcord extension to do it?
