### ISSUE TITLE
Ability to call a given command's required permission 

### ISSUE THREAD

**Issue by PearooXD** [nextcord/nextcord#511]
### Summary

It just returns what's in `@commands.has_permission()`.

### What is the feature request for?

nextcord.ext.commands

### The Problem

It'd be cool to have this in a help command that allows you to do `!help [command]`.

### The Ideal Solution

Probably something like `Command.required_permission`.

**Comment by MouseMoosz** [comment]
You would need to disable `self.verify_checks` in the `HelpCommand` class in `nextcord/ext/commands/help.py`.

**Comment by MaskDuck** [comment]
i think we'll need to have a huge codebase change since `@commands.has_permissions` only acts as a built-in before-invoke check.

**Comment by Skelmis** [comment]
It should be fairly trivial to implement, and non-breaking. I might give it a go sometime
