### ISSUE TITLE
Add image description to nextcord.File

### ISSUE THREAD

**Issue by error7404** [nextcord/nextcord#524]
### Summary

Add image description to nextcord.File

### What is the feature request for?

The core library

### The Problem

Not being able to write little text below images/gifs (and blind people).
![image](https://user-images.githubusercontent.com/48163201/157983484-c8feb880-e464-493b-868a-6d82169e0c24.png)

### The Ideal Solution

Add to `nextcord.File` an argument to add descriptions.

**Comment by DenverCoder1** [comment]
Working on it :+1:
