### ISSUE TITLE
Update Quickstart page in docs

### ISSUE THREAD

**Issue by DenverCoder1** [nextcord/nextcord#532]
[Quickstart](https://nextcord.readthedocs.io/en/latest/quickstart.html#quickstart) currently gives a bad example of doing message commands without ext.commands.

As this is not a recommended practice, the entire example should be rewritten, possibly using Slash Commands.

Also, `nextcord.Client` should be changed to `commands.Bot` to avoid confusion (as many features only support `commands.Bot`)

**Comment by MaskDuck** [comment]
i would do it ig
