### ISSUE TITLE
File constructor does not allow str

### ISSUE THREAD

**Issue by ooliver1** [nextcord/nextcord#543]
### Summary

The docs for File() do not say you can use a string path yet you can

### Reproduction Steps

View docs, view editor, view source 

### Minimal Reproducible Code

```python
n/a
```

### Expected Results

Str in typings and docs pls

### Actual Results

No typings and docs ;(

### Intents

N/a

### System Information

potato 

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

sorry for the memey completion of form

**Comment by DenverCoder1** [comment]
`bytes` is also accepted.

I can make a PR for this
