### ISSUE TITLE
No mentions, even using AllowedMentions

### ISSUE THREAD

**Issue by Varien-1936** [nextcord/nextcord#546]
### Summary

Mentions do not work when a command is executed

### Reproduction Steps

Added a reaction command to my bot, but after noticing there the author and/or member is not mentioned, got help and was told to add `AllowedMentions` in `bot = Commands.Bot` line but again, no mentions. Later told to add it on the `send` lines. Again, nothing.

### Minimal Reproducible Code

```python
#From the main.py

from os import listdir
from nextcord import *
from nextcord.ext.commands import Bot as Jeanne
from config import TOKEN

intents = Intents(guilds=True, members=True, messages=True,
                  typing=True, presences=True)
bot = Jeanne(command_prefix='/', intents=intents,
             allowed_mentions=AllowedMentions.all())
bot.remove_command('help')

#the command in the cog

from config import db
from nextcord import *
from nextcord import slash_command as jeanne_slash
from nextcord.ext.commands import Cog
from requests import get
from config import *



class slashreactions(Cog):
    def __init__(self, bot):
        self.bot = bot

    @jeanne_slash(description="Hug someone or yourself")
    async def hug(self, interaction: Interaction, member: Member = SlashOption(description="Who do you want to hug?", required=False)):
        await interaction.response.defer()
        try: #check if the author is botbanned
            botbanquery = db.execute(
                f"SELECT * FROM botbannedData WHERE user_id = {interaction.user.id}")
            botbanned_data = botbanquery.fetchone()
            botbanned = botbanned_data[0]
            reason = botbanned_data[1]

            botbanned_user = await self.bot.fetch_user(botbanned)
            if interaction.user.id == botbanned_user.id:
                await interaction.followup.send(f"You have been botbanned for:\n{reason}", ephemeral=True)
        except: #if the author's ID is not in the database
            hug_api = get(hug_nekoslife).json()
            if member == None:
                msg=f"*Hugging {interaction.user.mention}*"
            else:
                msg=f"*{interaction.user.mention} hugged {member.mention}*"
            hug = Embed(color=0xFFC0CB)
            hug.set_footer(text="Fetched from nekos.life")
            hug.set_image(url=hug_api["url"])
            await interaction.followup.send(msg, embed=hug)
```

### Expected Results

The author and/or member gets mentions after the command has been used

### Actual Results

No mentions, even with admin perm enabled or mentions allowed in the `send` lines.
![image](https://media.discordapp.net/attachments/955111158002630757/955820493338972250/unknown.png)

### Intents

members, guilds, messages, typing, presences 

### System Information

# from Windows PC
- Python v3.10.3-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a9
- aiohttp v3.8.1
- system info: Windows 10 10.0.19043

# from DigitalOceans Ubuntu
- Python v3.10.3-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a9
- aiohttp v3.8.1
- system info: Linux 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by DenverCoder1** [comment]
Ok, so this actually isn't possible.

I asked on the Discord Developers server.

Sending a followup to a deferred message is processed as message editing which sadly doesn't ping anyone.
