### ISSUE TITLE
channel.position often reflects creation order instead of sort order

### ISSUE THREAD

**Issue by sairam4123** [nextcord/nextcord#55]
### Link

https://github.com/Rapptz/discord.py/issues/2392

**Comment by ooliver1** [comment]
would most likely need
- docs improvement
- `__lt__` and the other 3 dunders maybe?
- possibly a real position - property - that checks against all channels for the official position

**Comment by ooliver1** [comment]
going to change this to a documentation edit as this is too much effort for something that discord causes entirely
