### ISSUE TITLE
Slash commands does not appear once defined

### ISSUE THREAD

**Issue by Corentin-Rougeon** [nextcord/nextcord#563]
### Summary

the slash command does not exist after creating it

### Reproduction Steps

make a simple slash command

### Minimal Reproducible Code

```python
from nextcord import Interaction
from nextcord.ext import commands
import nextcord

intents = nextcord.Intents.all()
client2 = commands.Bot(command_prefix='!', intents=intents)



@client2.event
async def on_ready():
    print("ready")
    print(client2.user.name)

@client2.slash_command(guild_ids=["521256432058761226"])
async def ping(interaction : Interaction):
    await interaction.response.send_message("pong")





client2.run("some token")
```

### Expected Results

the slash command should appear in the slash command suggestion

### Actual Results

![image](https://user-images.githubusercontent.com/70999237/161011659-c0d3d88a-1977-4295-ad37-d4891780bc0e.png)
the slash command is not there

### Intents

nextcord.Intents.all()

### System Information

- Python v3.10.0-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a10
- aiohttp v3.8.1
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Skelmis** [comment]
Guild id's are `int`'s not `str`'s.

You can refer to [these](https://nextcord.readthedocs.io/en/stable/api.html?highlight=slash_command#nextcord.Client.slash_command) docs as a refresher and hopefully, that solves your issue?

**Comment by Corentin-Rougeon** [comment]
> Guild id's are `int`'s not `str`'s.
> 
> You can refer to [these](https://nextcord.readthedocs.io/en/stable/api.html?highlight=slash_command#nextcord.Client.slash_command) docs as a refresher and hopefully, that solves your issue?

this solved it thanks.

tho I got one question, how do I make the slash commands work on every guild ?
I used 'force_global=True' without 'guild_ids=' but it doesn't work

**Comment by Skelmis** [comment]
Remove the `guild_ids` param and wait. Discord takes up to an hour to propagate your commands assuming you load them correct. They need to be loaded before ready so your bot can dispatch them.
