### ISSUE TITLE
bumping api version

### ISSUE THREAD

**Issue by MaskDuck** [nextcord/nextcord#572]
right now, bumping api version is really hard since it asks us to replace every version numbers. like when migrate to api v10, we must replace every number 9 with 10. it would be nice to have a variable contain api version so we could only changes a number when bumping api versions.

(note: ill implement this pls ty, just making the issue to see if there is agreement.)

**Comment by koala9712** [comment]
It needs to be changed in 3 files only iirc, and usually, api version changes are accompanied by various other fixes as well, to make the lib compatible to v10.
Is it worth it making a variable to avoid changing it 2 other places, while your anyways going to have to do multiple other changes as well?

**Comment by MaskDuck** [comment]
ic
