### ISSUE TITLE
Slash default_permission is always True

### ISSUE THREAD

**Issue by ooliver1** [nextcord/nextcord#575]
### Summary

default_permission defaults to true when it it set to anything Falsy

### Reproduction Steps

- have slash cmd
- set default_permission to False in the decorator
- wait
- see how it doesn't do anything 
- cry
- wonder if this was even tested
- ???
- pain
- wait for others to fix as it's too late for yourself
- question why discord even bothered with perms v1
- wonder what the point even is of anything
- sit there, alone, waiting for perms v2
- fix? pls

### Minimal Reproducible Code

```python
https://paste.nextcord.dev/?id=1649366267473687
```

### Expected Results

The default_permission to be False if set that way

### Actual Results

It will always be True and never function, shown via the payload 

### Intents

N/A

### System Information

h

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

https://discord.com/channels/881118111967883295/961047415438327808/961741853844209664

The very easy and simple line change can be found here too

**Comment by DenverCoder1** [comment]
This was brought up in #373

**Comment by ooliver1** [comment]
Aaa duplicate
