### ISSUE TITLE
support for multiple events with wait_for

### ISSUE THREAD

**Issue by Sup2point0** [nextcord/nextcord#577]
### Summary

`client.wait_for` currently only supports one event argument, but it would be useful if we could pass multiple

### What is the feature request for?

The core library

### The Problem

`client.wait_for` (and `bot.wait_for` in `ext.commands`) currently only accept a single event argument, but it would be very useful if multiple could be passed in (as a `list`, I'd imagine), to allow for flexibility.

### The Ideal Solution

Just something like this:
```py
await client.wait_for(["message", "reaction"], timeout = 120)
```

### The Current Solution

```py
done, pending = await asyncio.wait([
  bot.loop.create_task(bot.wait_for("message")),
  bot.loop.create_task(bot.wait_for("reaction")),
], return_when = asyncio.FIRST_COMPLETED)

try:
  stuff = done.pop().result()
except ...:
  pass
for future in done:
  future.exception()

for future in pending:
  future.cancel()
```
(code provided by @Soheab)

**Comment by ooliver1** [comment]
so i assume the return value is the first event that resolves, right?

**Comment by Sup2point0** [comment]
yup!

**Comment by TAG-Epic** [comment]
I dont see a reason for this to be added considering the current solution is decent and allows for much more flexibility (different checks per event)

**Comment by ooliver1** [comment]
The interface would be weird to the user as you have shown with your invalid `reaction` Event with `message`, one returns a tuple and one returns a single item
