### ISSUE TITLE
`typing.Literal`, `nextcord.Range` and `typing.Union` for choices + ranges + channel types

### ISSUE THREAD

**Issue by ooliver1** [nextcord/nextcord#585]
- [x] #589
- [x] #590
- [x] #591

### Summary

use `typing.Literal["some", "choices"]` instead of `SlashOption(choices=["some", "choices"])`, `nextcord.Range[1, 10]` instead of `SlashOption(min_value=1, max_value=10)` and `Union[Textchannel, VoiceChannel]` instead of `SlashOption(channel_types=[ChannelType.text, ChannelType.voice])`

### What is the feature request for?

Application commands

### The Problem

Currently, using `SlashOption` has been found to be slightly annoying to work with and pretty verbose in terms of syntax. Having a `Range` for min/max values and using `Literal` for choices will be more concise and less janky. Using `Union`'s (typing converts 3.10 piped unions to `typing.Union` I believe 

### The Ideal Solution

`typing.Literal[1, 2, 3]`
`nextcord.Range[min, max]`
`Union[Channel, Classes]`

### The Current Solution

`str: SlashOption(choices=[some, choices])`
`int/float: SlashOption(min_value=min, max_value=max)`
`GuildChannel = SlashOption(channel_types=[ChannelType's])`

**Comment by MaskDuck** [comment]
ill working on `typing.Literal` part for now.

**Comment by DenverCoder1** [comment]
Maybe allowing Enums for choices as well could be useful, especially when there are a lot of options or you are using it elsewhere and want to reduce redundancy.

**Comment by MaskDuck** [comment]
question, how do you rolling out slash commands?

**Comment by DenverCoder1** [comment]
> ill working on `typing.Literal` part for now.

I think Dysta said they are working on it already (about 5 hours ago). It was on the Discord server.

**Comment by DenverCoder1** [comment]
The relevant code to change would be the `CommandOption` constructor and/or the `CommandOption.get_type` method

**Comment by MaskDuck** [comment]
okay

**Comment by ooliver1** [comment]
I plan to split this issue into separate parts and include channel unions

**Comment by ooliver1** [comment]
#530 stalls this

**Comment by ToasterUwU** [comment]
This should not be stalled anymore, since the PR that stalled it, is merged now.

**Comment by EmreTech** [comment]
This should be moved from TODO because of the linked PR

**Comment by DenverCoder1** [comment]
It seems like the `Range` aspect is still not implemented so it won't be closed by #678

**Comment by ooliver1** [comment]
Anddddd, this is complete!
