### ISSUE TITLE
Document interaction permissions behaviour

### ISSUE THREAD

**Issue by ooliver1** [nextcord/nextcord#597]
### Summary

Document discord behaviour of message permissions inheriting from the `@everyone` role in interactions

### What is the feature request for?

The documentation

### The Problem

The discord behaviour of message permissions (mention `@everyone` here and all roles, use external emojis, ...) all inherit from the `@everyone` role's permissions when using interactions - discord behaviour. Something in the docs to note this would be awesome

### The Ideal Solution

An FAQ entry to describe the behaviour

### The Current Solution

Tell people asking for help the issue directly or use a tag

### Additional Context

Increasing amount of threads asking about the issue of this behaviour

**Comment by Soheab** [comment]
Discord is currently working on this as said in their [Developers Q&A](https://gist.github.com/Stalruth/8258cd0cd7298ffaed6290bc7ecadb8e#apps-and-api-updates#:~:text=Permissions%20for%20interactions)

**Comment by ooliver1** [comment]
closing this as the effort is not needed for something that will change
