### ISSUE TITLE
Set Embed Parameters in Instantiation

### ISSUE THREAD

**Issue by Sup2point0** [nextcord/nextcord#610]
### Summary

ability to directly set embed properties when creating the embed, rather than having to use separate methods afterwards to add them

### What is the feature request for?

The core library

### The Problem

Currently, not all embed properties can be set during instantiation, and instead must be set through separate methods afterwards:

```py
embed = nextcord.Embed(
  title = "Example",
  url = "...",
  description = "It'd be great if we could set everything in here",
  colour = 0x4090f1,
  timestamp = ...
)

embed.set_author(...)
embed.set_thumbnail(...)
embed.set_image(...)
embed.set_footer(...)
```

This can be quite cumbersome, and also means an embed must be instantiated prior to a message send, rather than directly within the send method:

```py
await interaction.send("...", embed = discord.Embed(
  ...
))
```

### The Ideal Solution

If possible, it'd be much more convenient if these other properties could be simply set directly:

```py
embed = nextcord.Embed(
  title = "Example",
  title_url = "...",
  author_url = "...",
  author_icon_url = "...",
  thumbnail = "...",
  description = "It'd be great if we could set everything in here",
  image = "...",
  colour = 0x4090f1,
  footer = "...",
  footer_icon_url = "...",
  timestamp = ...
)
```

### Additional Context

I imagine it was originally implemented this way to work with getters and setters with properties?

**Comment by DenverCoder1** [comment]
> and also means an embed must be instantiated prior to a message send, rather than directly within the send method

As it uses the builder design pattern (i.e. each of the setters return the new Embed), you _can_ actually instantiate it all in one line.

```py
interaction.send(
    "...",
    embed=discord.Embed(...)
    .set_author(...)
    .set_thumbnail(...)
    .set_image(...)
    .set_footer(...),
)
```

(not that I recommend doing so)

**Comment by DenverCoder1** [comment]
As a suggested alternative, you could make a method within your bot that sets accepts the attributes you need.

For example: The `build_embed` function in my [`embedder.py`](https://github.com/DenverCoder1/discord-bot-template/blob/main/utils/embedder.py).

**Comment by Sup2point0** [comment]
Oh they return the new embed? Huh, I thought I tried that and seem to remember it not working...

Well, if that’s the case there’s nothing to complain about :D guess this can be closed
