### ISSUE TITLE
Non bot token

### ISSUE THREAD

**Issue by fensoft** [nextcord/nextcord#629]
### Summary

Login as a non bot user

### What is the feature request for?

The core library

### The Problem

I'm developing a command line discord client. I want to port from discord.py 1.6.0 to nextcord but the client.run(bot=False) is missing. If I understand well, it's just a way of prefixing Bot in the Authorization header, see: https://github.com/Rapptz/discord.py/blob/v1.6.0/discord/http.py#L152

### The Ideal Solution

Add client.run(bot=False) feature.

**Comment by Skelmis** [comment]
Nextcord will not be adding the ability to interact as a non-bot user as that violates discord's terms of service assuming that's what you mean. 

But I will let Oliver or Epic answer definitively upon their interpretation

**Comment by ooliver1** [comment]
This violates ToS, discord does not want libraries to do this. We would be removed from the community resources page. Discord's viewpoint (and mine too) is you just use a bot account for automation, you don't need users for anything. If you need a user, take a think on if what you're doing is okay privacy-wise and safety-wise.
