### ISSUE TITLE
impossible to fetch avatar url from certain members

### ISSUE THREAD

**Issue by buxy-xyz** [nextcord/nextcord#632]
### Summary

avatar url is NoneType from some members

### Reproduction Steps

i get an error with the result NoneType whenever i try to pull the avatar url from discord accounts with default avatar.

this was possible in the old discord-py lib, seems to be only an issue in nextcord.

### Minimal Reproducible Code

```python
await channel.send( member.avatar.url )
```

### Expected Results

member.avatar.url shall fetch the actual avatar url instead of NoneType

### Actual Results

returned NoneType

### Intents

all

### System Information

- Python v3.10.4-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a10
- aiohttp v3.8.1
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

this works perfectly fine on members with an uploaded avatar.

**Comment by ooliver1** [comment]
This changed in discord.py 2.0, NAB. 

Use `display_avatar` to fallback to the `default_avatar` if they have no proper avatar. Or if you don't want to account for the guild avatar too, just fallback yourself if it is `None`.
