### ISSUE TITLE
`mypy` doesn't see atributes in `nextcord.ext.commands`

### ISSUE THREAD

**Issue by PerchunPak** [nextcord/nextcord#635]
### Summary

Title.

### Reproduction Steps

```console
$ cat example.py
from nextcord.ext.commands import Bot
$ mypy example.py
example.py:1: error: Module "nextcord.ext.commands" has no attribute "Bot"
```

### Expected Results

No errors in mypy.

### Actual Results

example.py:1: error: Module "nextcord.ext.commands" has no attribute "Bot"

### Intents

None

### System Information

```
- Python v3.10.4-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a10
- aiohttp v3.8.1
- system info: Linux 4.14.190-perf-g75e9984dc8e8 #1 SMP PREEMPT Tue Feb 15 22:26:40 CST 2022
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I also writed this in discord thread, but solution - set `implicit_reexport` to True not helped.

And possibly add `__all__` to `nextcord.ext.commands` will help.

**Comment by PerchunPak** [comment]
Caused by https://github.com/python/mypy/issues/4930. I will open PR with manual importing instead of `from name import *` imports.

**Comment by shiftinv** [comment]
I might be completely wrong about this, but the linked mypy issue seems unrelated? From experience this particular issue is usually resolved by running mypy with [`--namespace-packages`](https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules) or setting `namespace_packages = true` in the config, since `nextcord.ext` is a namespace package.

**Comment by PerchunPak** [comment]
Hmm, if this is actuall fix, PR should be closed.
I could open new PR for fixing this invalid `type: ignore` comments. Also, if I will found more invalid comments, fix them too.

**Comment by ooliver1** [comment]
that would be much better
