### ISSUE TITLE
Imports are broken

### ISSUE THREAD

**Issue by TAG-Epic** [nextcord/nextcord#64]
#52 fixed imports for ext.commands although this needs to be fixed throughout the entire aliased library

**Comment by rf20008** [comment]
discord.tasks are un-importable because nextcord.tasks does not exist

**Comment by TAG-Epic** [comment]
> discord.tasks are un-importable because nextcord.tasks does not exist

not a bug. Import is discord.ext.tasks

**Comment by rf20008** [comment]
> > discord.tasks are un-importable because nextcord.tasks does not exist
> 
> not a bug. Import is discord.ext.tasks

I also can't import discord.ext.tasks because I get a ModuleNotFoundError: No module named 'nextcord.tasks'

**Comment by redcreeper14385** [comment]
Yep, the init file should say `nextcord.ext.tasks`

**Comment by ooliver1** [comment]
Is this fixed from the new pull?

**Comment by ooliver1** [comment]
Again

**Comment by TAG-Epic** [comment]
Yeah haven't seen anyone have issues with the alias anymore.
