### ISSUE TITLE
Webhooks.send has different types between docstring and code

### ISSUE THREAD

**Issue by MajorTanya** [nextcord/nextcord#641]
Webhooks accept a keyword arg named `delete_after` of type `Optional[float]`.
The three method declarations in the code itself, however, all type `delete_after` as `Optional[bool]`.

I'm not sure if this poses any issues, but I thought something doesn't add up here. Especially considering that `delete_after` gets passed to msg.delete later, which takes a `float`.

Float docstring:
https://github.com/nextcord/nextcord/blob/7a53fb2b2fa4a760bdf050e3d08a64b93a53da0b/nextcord/webhook/async_.py#L1347

Bool declarations:
https://github.com/nextcord/nextcord/blob/7a53fb2b2fa4a760bdf050e3d08a64b93a53da0b/nextcord/webhook/async_.py#L1268
https://github.com/nextcord/nextcord/blob/7a53fb2b2fa4a760bdf050e3d08a64b93a53da0b/nextcord/webhook/async_.py#L1289
https://github.com/nextcord/nextcord/blob/7a53fb2b2fa4a760bdf050e3d08a64b93a53da0b/nextcord/webhook/async_.py#L1309

Passing to msg.delete:
https://github.com/nextcord/nextcord/blob/7a53fb2b2fa4a760bdf050e3d08a64b93a53da0b/nextcord/webhook/async_.py#L1462

**Comment by ooliver1** [comment]
#627
