### ISSUE TITLE
`InvalidEmbed` error instead of `HTTPException`

### ISSUE THREAD

**Issue by codeman1o1** [nextcord/nextcord#646]
### Summary

Raise a new error for when an embed is invalid (`InvalidEmbed`)

### What is the feature request for?

The core library

### The Problem

Currently, when you are trying to send an invalid embed, it raises `HTTPException`.
For a new user, it is unclear that it is caused by an invalid embed and can cause confusion

### The Ideal Solution

A new error called `InvalidEmbed` or something along those lines that raises when an invalid embed was sent

**Comment by TAG-Epic** [comment]
Not possible without a large amount of weird workarounds.

**Comment by ooliver1** [comment]
to expand on that

discord has a lot of verification it does on embed objects and doing that in the library would be "slow" but also complex
