### ISSUE TITLE
Client.get_partial_messageable().send() is not sending a message

### ISSUE THREAD

**Issue by janasolo9** [nextcord/nextcord#651]
### Summary

The PartialMessageable object send method does not send message.

### Reproduction Steps

Steps that I did:
1. partial_channel = Client.get_partial_messageable(my dm_channel ID, type = ChannelType.private)
2. await partial_channel.send(embed = some embed)

In the source code, this looks like
1. `bot.get_partial_messageable` creates a `PartialMessageable` object
2. The `PartialMessageable` has an attribute channel which is initialized as `Object(id = id)`
3. `PartialMessageable.send` calls `ConnectionState.create_message(channel, data)` where channel is the Object and data is stuff from `await state.http.send_message`
4. `ConnectionState.create_message` creates a new Message object with `Message(state, channel, data)`
5. `Message.__init__` attempts to get the guild attribute and type attribute from channel (which is an Object object).

Traceback can be found here: https://paste.nextcord.dev/?id=1652901053415284

### Minimal Reproducible Code

```python
bot = commands.Bot()
user = bot.get_user(MY ID)
dm_channel = user.dm_channel if user.dm_channel else await user.create_dm()
partial_channel = bot.get_partial_messageable(dm_channel.id, type = ChannelType.private)
await partial_channel.send(embed = some embed)
```

### Expected Results

I expected the message to be sent with the `PartialMessageable` object.

### Actual Results

The `Message.__init__` attempts to check the guild attribute and type attribute of the "channel" object, but `channel` is an Object object.

### Intents

nextcord.Intents.default() with intent.members = True

### System Information

- Python v3.10.1-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a10
- aiohttp v3.8.1
- system info: Windows 10 10.0.19043

### Checklist

- [ ] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by DenverCoder1** [comment]
> bot = commands.Bot()
user = bot.get_user(MY ID)
dm_channel = user.dm_channel if user.dm_channel else await user.create_dm()
partial_channel = bot.get_partial_messageable(dm_channel.id, type = ChannelType.private)
await partial_channel.send(embed = some embed)

Side note... can't you just use [`user.send()`](https://docs.nextcord.dev/en/latest/api.html?highlight=user%20send#nextcord.User.send)? As the docs say, [`create_dm()`](https://docs.nextcord.dev/en/latest/api.html?highlight=user%20send#nextcord.Client.create_dm) should rarely be called.

**Comment by janasolo9** [comment]
I'm future proofing the bot. I have `chunk_guilds_at_startup = False`, so `bot.users` is empty and `bot.get_user` will always return None. My code is in a task.loop set for every 30 minutes to send messages to users who sign up, and I don't want to `bot.fetch_user` for potentially a lot of users every 30 minutes. The alternative is to cache the users myself in a botvar when they sign up for notifications from my bot.

**Comment by DenverCoder1** [comment]
When I test the sample code you sent, it does *send* the message, but it runs into an attribute error when creating a Message object afterwards.

Is that what you are seeing?
