### ISSUE TITLE
Adding attributes for the new `TEXT_IN_VOICE` guild feature

### ISSUE THREAD

**Issue by toolifelesstocode** [nextcord/nextcord#655]
### Summary

This issue just gives information on what happens when nextcord interacts with the new guild feature.

### What is the feature request for?

The core library

### The Problem

Many of us know that `nextcord.VoiceChannel` does not have a `send` method/function. Recently, Discord added a new `TEXT_IN_VOICE` guild feature, which makes the library make it `VoiceChannel.send` in which, which causes it to fail when trying to reply/send a message in a Voice Text channel. Here is an image of what happens when I try it:
![image](https://user-images.githubusercontent.com/80943664/171590771-d4bae25f-a53f-47a1-a869-ed28dc951575.png)

### The Ideal Solution

Adding the `TEXT_IN_VOICE` feature to nextcord, and adding the valid attributes. When Discord fully releases it, since I've heard that it is not on all platforms and that Discord just released it early.

### The Current Solution

From my side, I have not seen any `TEXT_IN_VOICE` stuff on the Discord Developer documentation, so for now we would have to wait for it to be there(at least, I think that's how you guys check and add stuff 😅).

### Additional Context

This issue is a bit more informational than #654 I would think. Oh and also, A bit more user-friendly information is on this [Discord Article](https://support.discord.com/hc/en-us/articles/4412085582359)

**Comment by iosif2** [comment]
[Discord API Create Message](https://discord.com/developers/docs/resources/channel#create-message)
This endpoint is working properly with the VoiceChannel
