### ISSUE TITLE
the docs is wrong

### ISSUE THREAD

**Issue by MaskDuck** [nextcord/nextcord#667]
### Summary

[Interaction.client](https://docs.nextcord.dev/en/stable/api.html#nextcord.Interaction.client) return section fucked up

### Reproduction Steps

- have a bot
- listen to `on_interaction`
- print `type(interaction.client)`

### Minimal Reproducible Code

```python
import nextcord
from nextcord.ext import commands

intents = nextcord.Intents.all()

bot = commands.Bot(command_prefix="h", intents=intents)

@bot.event
async def on_interaction(interaction):
  print(type(interaction.client))
  await bot.process_application_commands(interaction)

bot.run()
```

### Expected Results

per docs, `nextcord.Client`

### Actual Results

`commands.Bot`

### Intents

above

### System Information

- Python v3.10.4-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0b3
- aiohttp v3.8.1
- system info: Linux 5.4.0-1074-azure #77~18.04.1-Ubuntu SMP Wed Mar 30 15:36:02 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

i can work for this

**Comment by ooliver1** [comment]
commands.Bot is a subclass of nextcord.Client, once again please stop using swear words on GitHub, I like to keep this clean

**Comment by MaskDuck** [comment]
> commands.Bot is a subclass of nextcord.Client, once again please stop using swear words on GitHub, I like to keep this clean

ic, sorry
