### ISSUE TITLE
Changing the name "Danny" to "Rapptz" on the About section

### ISSUE THREAD

**Issue by toolifelesstocode** [nextcord/nextcord#718]
I think that the name on the repository "About" section should change from Danny to Rapptz, as I doubt many people would know who "Danny" is, but would most likely know who Rapptz is, as they are known to be the Discord.py developer. 
![image](https://user-images.githubusercontent.com/80943664/176269599-809615f0-3084-4a38-9b49-cf93413ab9fc.png)
^ So this would be changed to `A maintained fork of Rapptz' discord.py`

**Comment by toolifelesstocode** [comment]
If not, then it should at least match the PyPI description for consistency, `A Python wrapper for the Discord API forked from discord.py`

**Comment by ooliver1** [comment]
changed to `A Python wrapper for the Discord API forked from discord.py`
