### ISSUE TITLE
Several IDE Warnings from: nextcord.utils.get(client.voice_clients, guild=ctx.guild)

### ISSUE THREAD

**Issue by ElectricEvan** [nextcord/nextcord#729]
### Summary

nextcord.utils.get is of type VoiceClient, but IDEs see it as VoiceProtocol

### Reproduction Steps

vc_connection = await ctx.author.voice.channel.connect()
print(vc_connection.is_playing()) 
-
If we get the VoiceClient like this, the type printed is VoiceClient and IDE shows no warnings 

vc_connection = nextcord.utils.get(client.voice_clients, guild=ctx.guild)
print(vc_connection.is_playing()) 
-
If we get the VoiceClient like this, the type printed is VoiceClient and **the code still works**, but the IDE shows warnings because it sees it as VoiceProtocol which doesn't have the same methods as VoiceClient.

### Minimal Reproducible Code

```python
async def check_voice(ctx):
    if ctx.author.voice:
        vc = ctx.author.voice.channel
    else:
        return await ctx.reply("You must be in a voice channel to use music commands")

    # Connect to requester's VC, unless already connected
    try:
        vc_connection = await vc.connect()
        print(vc_connection.is_playing())
    except nextcord.errors.ClientException:
        vc_connection = nextcord.utils.get(client.voice_clients, guild=ctx.guild)
        print(vc_connection.is_playing())
```

### Expected Results

IDE should nextcord.utils.get(client.voice_clients, guild=ctx.guild) as type VoiceClient

### Actual Results

IDE sees nextcord.utils.get(client.voice_clients, guild=ctx.guild) as type VoiceProtocol rather than VoiceClient

### Intents

nextcord.Intents.all()

### System Information

- Python v3.10.5-final
- nextcord v2.0.0-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.22000

All libraries should be up to date (checked with pip list --outdated)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I actually just migrated to nextcord from the original discord repo. The original discord repo did not have these IDE warnings. I would also like to note (in case relevent) that the python version was recently upgraded from 3.9 to 3.10, and a whole bunch of libraries were upgraded to their latest versions.

**Comment by DenverCoder1** [comment]
Not a bug since [client.voice_clients](https://docs.nextcord.dev/en/latest/api.html#nextcord.Client.voice_clients) is a list of VoiceProtocol. These are usually [VoiceClient](https://docs.nextcord.dev/en/latest/api.html?highlight=voice_clients#discord.VoiceClient) instances, but they don't have to be.

This is expected when dealing with type checkers that sometimes methods will return a type that is a superclass of the type they really are.

If you know you are only dealing with VoiceClients, possible solutions include:

```py
assert isinstance(vc_connection, VoiceClient)
```

Or 
```py
print(vc_connection.is_playing())  # type: ignore
```

**Comment by ElectricEvan** [comment]
That's pretty cool!  I didn't know you could comment out warnings like that.

Is there a particular reason why IDEs only complains about it in nextcord, but not the original discord.py?

**Comment by DenverCoder1** [comment]
I doubt that's the case since the [docs](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.voice_clients) show it's the same.

It's possible you changed your type checking settings between migrating.

**Comment by ElectricEvan** [comment]
I just checked my code again, replacing nextcord with discord and the warnings did go away. If I replace discord with nextcord in my code, then the warnings do appear. Are you getting different results when switching between the two libraries? What IDE are you using?

I also thought it was weird because like you said, the docs show pretty much the same stuff.

**Comment by DenverCoder1** [comment]
I have a virtual environment with discord.py 2.0 and testing out the code you sent gives the same results for me.

![image](https://user-images.githubusercontent.com/20955511/177213048-8300f6b2-70b6-4657-a18c-64b4de0beabc.png)

**Comment by ElectricEvan** [comment]
Hmm. That's really interesting. I think I'll just blame it on PyCharm or other factors being wack and call it a day then, since we cannot seem to replicate the issue between the two libraries. Thanks for confirming the results with me!
