### ISSUE TITLE
Give Bots the Ability to Reply in Voice Channel Chat Window

### ISSUE THREAD

**Issue by ElectricEvan** [nextcord/nextcord#730]
### Summary

Discord recently added chat windows for voice channels. Although bots are still able to ctx.send(), they cannot ctx.reply()

### What is the feature request for?

The core library

### The Problem

![image](https://user-images.githubusercontent.com/32850711/177207839-223ba6ae-ceaf-4723-921d-6f6c88482225.png)
Since bots can't reply in the voice channel's chat window as shown above, the following error is outputted instead:

`Traceback (most recent call last):
  File "C:\Users\Evan_\AppData\Local\Programs\Python\Python310\lib\nextcord\ext\commands\bot.py", line 1117, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Evan_\AppData\Local\Programs\Python\Python310\lib\nextcord\ext\commands\core.py", line 948, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Evan_\AppData\Local\Programs\Python\Python310\lib\nextcord\ext\commands\core.py", line 174, in wrapped
    raise CommandInvokeError(exc) from exc
nextcord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'VoiceChannel' object has no attribute 'send'`

Adding the ctx.reply() feature in the voice channel's chat window allows better user experience with bots, especially ones that utilise voice channels often.

### The Ideal Solution

When ctx.reply() is invoked in the voice channel's chat window, no errors should be raised and ctx.reply() should work as normal.

### The Current Solution

ctx.send() does work in voice channel chat windows and does the job of sending messages and embeds, but loses on the actual replying mechanics from ctx.reply()

**Comment by EmreTech** [comment]
This is already implemented in the GitHub version (2.1 alpha 0).

**Comment by ooliver1** [comment]
Will come next release, use the GitHub version for now
