### ISSUE TITLE
Reload breaks anything autocomplete-related

### ISSUE THREAD

**Issue by PearooXD** [nextcord/nextcord#737]
### Summary

Using `Client.reload_extension` breaks autocomplete in slash commands.

### Reproduction Steps

I'm using `Client.reload_extension` for reloading a file full of slash commands, however it breaks my autocomplete and therefore it just doesn't work for some reason.

### Minimal Reproducible Code

```python
@commands.command
async def reload(ctx, extension):
    client.reload_extension(f"cogs.{extension}")
    await ctx.send("Reloaded!")

@nextcord.slash_command(guild_ids=[123456789], description="Your favorite dogs!")
async def favorite_dogs(interaction, dog: str=nextcord.SlashOption(name="dog", description="Your favorite dog's breed.")):
    await ctx.send("Your favorite dog is {}!".format(dog))

@favorite_dogs.on_autocomplete("dog")
async def favorite_dog_autocomplete(interaction, dog: str):
    if not dog:
        await interaction.response.send_autocomplete(["husky", "idk dog breeds"])
        return
    await interaction.response.send_autocomplete([i for i in ["husky", "idk dog breeds"] if i.lower().startswith(dog.lower())])
```

### Expected Results

Well... for it to work.

### Actual Results

It didn't work.
Error: `ValueError: Received autocomplete interaction for warn but command isn't found/associated!` (it worked before reloading)

### Intents

nextcord.Intents.default() and message content.

### System Information

- Python v3.10.5-final
- nextcord v2.0.0-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.22622

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Skelmis** [comment]
This Minimal Reproducible Code appears to be missing self. Are you sure these cogs are setup correctly?

**Comment by Pearoo-XD** [comment]
> This Minimal Reproducible Code appears to be missing self. Are you sure these cogs are setup correctly?

i wrote the reproducible code by hand, so thats not the problem.
also i just edited it, i forgot to paste the error.

**Comment by Skelmis** [comment]
There are no specifics for only a Cog, however, you can use [this](https://docs.nextcord.dev/en/stable/api.html?highlight=sync_all#nextcord.Client.sync_all_application_commands) after you load a cog in order to sync application commands on your bot.
If you wanted to provide more specific params, such as specific guilds or global you can look into [this](https://docs.nextcord.dev/en/stable/api.html?highlight=sync_all#nextcord.Client.sync_application_commands) method.

This fixed the issue for my test bot, however, if your reloading your cogs *a lot* it may pay to look into alternatives as this does require hitting the API.

**Comment by Pearoo-XD** [comment]
> There are no specifics for only a Cog, however, you can use [this](https://docs.nextcord.dev/en/stable/api.html?highlight=sync_all#nextcord.Client.sync_all_application_commands) after you load a cog in order to sync application commands on your bot. If you wanted to provide more specific params, such as specific guilds or global you can look into [this](https://docs.nextcord.dev/en/stable/api.html?highlight=sync_all#nextcord.Client.sync_application_commands) method.
> 
> This fixed the issue for my test bot, however, if your reloading your cogs _a lot_ it may pay to look into alternatives as this does require hitting the API.

it fixed the issue for my bot too, but i think this should still be fixed to not cause further problems

**Comment by alentoghostflame** [comment]
Heyo! When a cog is unloaded, all information the bot has about the application commands in that cog is removed from cache, such as what command ID's correspond to what callbacks. When a cog is (re)added to the bot, the bot will have the new application commands added locally, but won't know their command IDs.

In order for the bot to figure out what command IDs should be routed to which callbacks it needs to do at least one HTTP request to Discord for global commands, and at least one request per guild that your bot/cog has at least one application command for. Mix Discord enforcing rate limiting to keep people from hitting their platform too hard, and that puts things in a slightly awkward position.

Either NC would resync your commands for you every time you reload a cog, hitting Discord with HTTP requests behind the scenes, or the bot dev should manually call sync_all_application_commands when their cog(s) are all reloaded. I suppose a kwarg could be added to Client/Bot for syncing behind the scenes, but hmm.

**Comment by ooliver1** [comment]
> Heyo! When a cog is unloaded, all information the bot has about the application commands in that cog is removed from cache, such as what command ID's correspond to what callbacks. When a cog is (re)added to the bot, the bot will have the new application commands added locally, but won't know their command IDs.
> 
> In order for the bot to figure out what command IDs should be routed to which callbacks it needs to do at least one HTTP request to Discord for global commands, and at least one request per guild that your bot/cog has application commands for. Mix Discord enforcing rate limiting to keep people from hitting their platform too hard, and that puts things in a slightly awkward position HTTP-wise.
> 
> Either NC would resync your commands for you every time you reload a cog, hitting Discord with HTTP requests behind the scenes, or the bot dev should manually call sync_all_application_commands when their cog(s) are all reloaded. I suppose a kwarg could be added to Client/Bot for syncing behind the scenes, but hmm.

I personally would be all for adding a kwarg to `Bot`, as there are already lots of requests that happen "behind the scenes" such as deleting unknown commands and syncing on connect. Documentation would have to most likely be edited to explain why `(un)load_extension` does not sync application commands by itself by default.
