### ISSUE TITLE
nextcord.ui.Select items in Modals do not return "values" in callback (in a cog)

### ISSUE THREAD

**Issue by Joshua-Wilcox** [nextcord/nextcord#749]
### Summary

When adding a "nextcord.ui.Select" Item to a modal. The values selected can not be accessed in the callback.

### Reproduction Steps

- Went to [Nextcord Modal Example](https://github.com/nextcord/nextcord/blob/master/examples/modals/modal.py)
- Pasted the "Pet" class 
- Created a simple command that sends the modal
- Filled in the Modal
- Got an error.

## Error Traceback
```py 
line 261, in _scheduled_task
    await self.callback(interaction)
line 60, in callback
    response += f"\nThe type of pet is {self.pet_type.values[0]}."
IndexError: list index out of range

````

### Minimal Reproducible Code

```python
#THIS ISNT MY FULL CODE!!!! - I have taken out what i deem to be relevant
#Line 20
class Pet(nextcord.ui.Modal):
    def __init__(self):
        super().__init__(
            "Your pet",
            timeout=5 * 60,  # 5 minutes
        )

        self.name = nextcord.ui.TextInput(
            label="Your pet's name",
            min_length=2,
            max_length=50,
        )
        self.add_item(self.name)

        self.description = nextcord.ui.TextInput(
            label="Description",
            style=nextcord.TextInputStyle.paragraph,
            placeholder="Information that can help us recognise your pet",
            required=False,
            max_length=1800,
        )
        self.add_item(self.description)

        self.pet_type = nextcord.ui.Select(
            options=[
                nextcord.SelectOption(label="Dog", emoji="🐶"),
                nextcord.SelectOption(label="Cat", emoji="🐱"),
                nextcord.SelectOption(label="Bird", emoji="🐦"),
                nextcord.SelectOption(label="Fish", emoji="🐟"),
                nextcord.SelectOption(label="Other", emoji="🐰"),
            ],
            min_values=1,
            max_values=1,
            placeholder="Type of pet",
        )
        self.add_item(self.pet_type)

    async def callback(self, interaction: nextcord.Interaction) -> None:
        response = f"{interaction.user.mention}'s favourite pet's name is {self.name.value}."
        response += f"\nThe type of pet is {self.pet_type.values[0]}."
        if self.description.value != "":
            response += (
                f"\nTheir pet can be recognized by this information:\n{self.description.value}"
            )
        await interaction.send(response)

#Line 331
class subjectSetup(commands.Cog):
    def __init__(self, client: nextcord.Client):
        self.client: nextcord.Client = client

        @client.slash_command(
            name='test',
            description='test',
        )
        async def test(interaction: Interaction):
            modal = Pet()
            await interaction.response.send_modal(modal)


def setup(client):
    client.add_cog(subjectSetup(client))
```

### Expected Results

I expected ```self.pet_type.values``` to have an entry which corresponded to my input in the modal

### Actual Results

```self.pet_type.values``` did not have any value therefore 
```py
response += f"\nThe type of pet is {self.pet_type.values[0]}."
``` 
caused an IndexError when it shouldn't have

### Intents

intents = nextcord.Intents.default() intents.voice_states = True intents.members = True intents.presences = True intents.reactions = True intents.guilds = True

### System Information

- Python v3.10.4-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a10
- aiohttp v3.8.1
- system info: Darwin 22.0.0 Darwin Kernel Version 22.0.0: Tue Jun 28 20:46:36 PDT 2022; root:xnu-8792.0.134.131.2~1/RELEASE_ARM64_T6000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Note that I am running this in a Cog - may be causing issues idk
This is my first bug report - I hope it is easy enough to understand and meets standards correctly

**Comment by DenverCoder1** [comment]
You are using an old version of nextcord. Select in modals was not supported until 2.0.0b1. The latest is 2.0.0 stable.

Also note that Discord still does not support select menus at all on mobile.

**Comment by Joshua-Wilcox** [comment]
> You are using an old version of nextcord. Select in modals was not supported until 2.0.0b1. The latest is 2.0.0 stable.
> 
> Also note that Discord still does not support select menus at all on mobile.

I will look into getting a later version.
Select menu's are currently a necessity for my planned usecase but I will look into other options.
I'll update this issue if updating to a later version fixes the original issue

**Comment by Joshua-Wilcox** [comment]
Updating nextcord fixed it

**Comment by ooliver1** [comment]
Please use the latest version from PyPI before submitting issues.
