### ISSUE TITLE
Embed has no attribute Empty

### ISSUE THREAD

**Issue by killuazoldyckreal** [nextcord/nextcord#751]
### Summary

when i tried to make thumbnail url empty this error arised

### Reproduction Steps

```py
@commands.command(aliases=['em'])
@commands.bot_has_guild_permissions(embed_links=True)
async def embi(self, interaction:Interaction,channel:nextcord.TextChannel=None):
    embed=nextcord.Embed(title="Title",description="Description",color=0x0000ff)
    embed.set_author(name=self.bot.user.name, icon_url=self.bot.user.avatar.url)
    embed.set_thumbnail(url='https://i.imgur.com/3F1v6Ej.png')
    embed.set_thumbnail(url=Embed.Empty)
    embed.set_image(url='https://i.imgur.com/D8PTquX.png')
    embed.set_footer(text='Footer',icon_url=self.bot.user.avatar.url)
    view=Eviews(embed,channel,self.bot)
    await interaction.send(embed=embed)
```

### Minimal Reproducible Code

```python
@commands.command(aliases=['em'])
@commands.bot_has_guild_permissions(embed_links=True)
async def embi(self, interaction:Interaction):
    embed=nextcord.Embed(description="Description",color=0x0000ff)
    embed.set_thumbnail(url='https://i.imgur.com/3F1v6Ej.png')
    embed.set_thumbnail(url=Embed.Empty)
    await interaction.send(embed=embed)
```

### Expected Results

I was hoping the thumbnail would be removed.

### Actual Results

```Ignoring exception in command embi:
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python39\lib\site-packages\nextcord\ext\commands\core.py", line 165, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Dell\Desktop\babyhawk\modules\embed\cog.py", line 176, in embi
    embed.set_thumbnail(url=Embed.Empty)
AttributeError: type object 'Embed' has no attribute 'Empty'
```

### Intents

nextcord.Intents.all()

### System Information

- Python v3.9.11-final
- nextcord v2.0.0-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I am sorry if there is any fault from my side, I thought it is a sort of bug or error in nextcord library, so i am sharing it with fair intentions. I don't want to disturb any of the helpers maintaining this fabulous library.

**Comment by elpablo5542** [comment]
you need to use nextcord.Embed.Empty
(docs: https://docs.nextcord.dev/en/stable/api.html?highlight=embed%20empty#nextcord.Embed.Empty)

**Comment by killuazoldyckreal** [comment]
> 

bro i have imported Embed attribute, why would i use that
`from nextcord import Embed`

**Comment by DenverCoder1** [comment]
It is an attribute of embeds, try using `embed.Empty` with lowercase.

https://github.com/nextcord/nextcord/blob/5f02c3374b94c7dfe28cc375c38a598f110fee4f/nextcord/embeds.py#L186

You can see from the code that the Embed field is a singleton called `EmptyEmbed`, so you can also import that from nextcord.embeds instead if you prefer (this way is undocumented, however).

**Comment by killuazoldyckreal** [comment]
sorry this all mess created cause i had the cog named Embed, i really regret this silly mistake
