### ISSUE TITLE
Custom Interactions

### ISSUE THREAD

**Issue by Soumeh** [nextcord/nextcord#757]
### Summary

a `get_context()` alternative for slash command Interaction objects

### What is the feature request for?

Application commands

### The Problem

Currently, custom functions cannot be applied to `Interaction` objects like they can to the `Context` object used in normal commands

### The Ideal Solution

A `get_application()` method gets added to the `Client` object.

**Comment by TAG-Epic** [comment]
Something like this is planned for NCv3.

**Comment by Skelmis** [comment]
In terms of implementation details, adding something like `get_interaction(..., cls=...)` shouldn't be too hard. Currently this is hard coded [here](https://github.com/nextcord/nextcord/blob/master/nextcord/state.py#L1370), but could easily be changed to use a method on the client or alternately as a reference to the object passed to `Client`'s init
