### ISSUE TITLE
Search queries duplicating when searching with the `nextcord` namespace

### ISSUE THREAD

**Issue by toolifelesstocode** [nextcord/nextcord#758]
### Summary

When searching `nextcord.{SomeClass}`, it shows the result, as well as it's attributes twice.

### Reproduction Steps

1. Going to the documentation
2. Searching `nextcord.TextChannel`, along with some other classes to test

### Expected Results

It should just show `nextcord.TextChannel`, or generally any class and it's attributes once, whether it has the `nextcord.` athe beginning or not.

### Actual Results

It would show the results and attributes of, said class, twice:
![image](https://user-images.githubusercontent.com/80943664/182201388-bcb25bbc-0aac-46de-af09-b32832174486.png)

### Intents

[No Intents]

### System Information

Firefox Nightly 105.0a1 (2022-08-01) (64-bit)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

It would seem that this is something that came from discord.py, as almost all the forks, as well as discord.py have this exact same bug.

**Comment by shiftinv** [comment]
This happens due to a sphinx bug, fixed in sphinx 5.0: https://github.com/sphinx-doc/sphinx/issues/10227
Unfortunately wasn't backported to 4.x, so the solution is either upgrading to 5.0 or bundling a patched `searchtools.js`.

**Comment by toolifelesstocode** [comment]
> This happens due to a sphinx bug, fixed in sphinx 5.0: [sphinx-doc/sphinx#10227](https://github.com/sphinx-doc/sphinx/issues/10227) Unfortunately wasn't backported to 4.x, so the solution is either upgrading to 5.0 or bundling a patched `searchtools.js`.

Ahh, thank you, I suppose upgrading would be the best solution.
