### ISSUE TITLE
I want to add an error when the message limit exeeds the 2000 

### ISSUE THREAD

**Issue by Ahmed3457** [nextcord/nextcord#765]
### Summary

I want to add an error when the message limit exeeds the 2000 It Would Be Really useful  

### What is the feature request for?

nextcord.ext.commands

### The Problem

I want to add an error when the message limit exeeds the 2000 It Would Be Really useful Beacause i am making a bot it's open source i have a lyrics command i want whenever the message limit exeeds it gives me and error to add some sort of exeption (The Link of my bot repo in case you want to check https://github.com/Ahmed3457/eXtreme-Discord-Bot/)

### The Ideal Solution

To give and error in the console just like when someone forgets a required argument

**Comment by ooliver1** [comment]
Nextcord leaves most validation like this up to Discord, you can either truncate your lyrics or pagínate it with something like [nextcord.ext.menus](https://github.com/nextcord/nextcord-ext-menus)

**Comment by Soheab** [comment]
You can do this by handling the `50035` from the JSON [OP-CODES](https://discord.com/developers/docs/topics/opcodes-and-status-codes#json)
Note: unfortunately `50035` is not only for exceeding the 2000 limit but rather for anything in the request body. An if 
-statement can be used to check if it's the content.

All of that should result in something like the following:
```py
# error handling function 
# can be on_error, on_command_error, etc

# catch HTTPException
# should be accessible from the `nextcord.` module.
if isinstance(<error>, HTTPException):
    # check if it's the right OP-CODE
    if <error>.code == 50035:
        # check if it's an error in the content field
        if "In-Content:" in <error>.message:
            # handle the error that happened in the content field
            # optional: to make sure it's the 2000 characters exceeded error, we can check the exact error with another if-statement:
            # if "Must be 2000 or fewer in length" in <error>.message:
            print("Content was over 2000 characters!")
            
            return
```
Or... check `if len(<message>) > 2000:` in the command before sending 🤷🏼

**Comment by ooliver1** [comment]
You can also use an embed description, which means truncating the lyrics has less effect as the limit is `4096` characters.
