### ISSUE TITLE
Slash command does not keep docstring

### ISSUE THREAD

**Issue by codeman1o1** [nextcord/nextcord#767]
### Summary

Slash command does not keep docstring

### Reproduction Steps

1. Make a basic slash command with a docstring
2. Open a Python shell in the same directory
3. Import the bot file
4. Get the docstring (`mycommand.__doc__`)
5. See nothing

### Minimal Reproducible Code

```python
@bot.slash_command()
async def ping(interaction: nextcord.Interaction):
    """Replies with Pong"""
    await interaction.send("Pong!", ephemeral=True)
```

### Expected Results

Show the docstring

### Actual Results

Shows nothing

### Intents

None, (none are needed for slash commands)

### System Information

- Python v3.10.6-final
- nextcord v2.1.0-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The docstring does appear in the slash command description.

**Comment by DenverCoder1** [comment]
This is expected behavior.

Using the decorator converts the function into a `SlashApplicationCommand` object. You can access the original callback using the `SlashApplicationCommand.callback` attribute.

```py
mycommand.callback.__doc__
```

This works similarly for ext commands.

**Comment by codeman1o1** [comment]
Okay, thanks for the clarification!
