### ISSUE TITLE
Slash Command Not Showing 

### ISSUE THREAD

**Issue by Ahmed3457** [nextcord/nextcord#776]
### Summary

There is a problem with slash commands going on 

### Reproduction Steps

tryed to make a slash command it didn't appear 

### Minimal Reproducible Code

```python
import nextcord
from nextcord.ext import commands

TESTING_GUILD_ID = 1007085593513164890 # Replace with your testing guild id


class ApplicationCommandCog(commands.Cog):
    def __init__(self, client):
        self.client = client

    
    @nextcord.user_command(guild_ids=[TESTING_GUILD_ID])
    async def my_user_command(self, interaction: nextcord.Interaction, member: nextcord.Member):
        await interaction.response.send_message(f"Hello, {member}!")

    @nextcord.message_command(guild_ids=[TESTING_GUILD_ID])
    async def my_message_command(
        self, interaction: nextcord.Interaction, message: nextcord.Message
    ):
        await interaction.response.send_message(f"{message}")


def setup(client):
    client.add_cog(ApplicationCommandCog(client))
```

### Expected Results

A slash command to appear

### Actual Results

The command didn't appear when i typed /

### Intents

intents = nextcord.Intents.default() intents.members = True intents.message_content = True client=commands.Bot(command_prefix='-',intents=intents,help_command=None, case_insensitive=True)

### System Information

- Python v3.8.0-final
- nextcord v2.1.0-final
- aiohttp v3.8.1
- system info: Windows 7 6.1.7601

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

If you wanna check the full code go to https://github.com/Ahmed3457/eXtreme-Discord-Bot

**Comment by EmreTech** [comment]
These are Context Menu Commands, you have to right click on a user or message then go to the apps section and your commands will be there

**Comment by ooliver1** [comment]
You likely want `slash_command`, as that is for the chat input commands with the `/` invocation
