### ISSUE TITLE
My slash commands do not register on nextcord

### ISSUE THREAD

**Issue by konsttheogr** [nextcord/nextcord#789]
### Summary

My slash commands do not register on nextcord

### Reproduction Steps

My nextcord slash commands do not register on discord anymore. They did, until one moment i saw they would not anymore. My old ones are registered, and do update. I haven't changed absolutely anything to the new commands, and i don't know what's wrong. One command that isn't working is shown below. Any help is welcome.

### Minimal Reproducible Code

```python
@client.slash_command(description="Reveals a text after some drums.", guild_ids=guilds)
async def drums(interaction: Interaction, message):
    embed1 = nextcord.Embed(title="drums", description="")
    embed1.set_image(
        url=
        'https://media1.tenor.com/images/908d4d6030400cc6bcd7ba76d897922c/tenor.gif?itemid=11982656'
    )
    embed2 = nextcord.Embed(title='drums ??????????',
                            description=str(interaction.user) + ': ' + message)
    msgg = await interaction.send_message(embed=embed1)
    await asyncio.sleep(5)
    await msgg.edit(embed=embed2)
```

### Expected Results

Slash command to show up

### Actual Results

It didn't show up when i typed /

### Intents

nextcord.Intents.All()

### System Information

- Python v3.8.12-final
- nextcord v2.0.0-final
- aiohttp v3.8.1
- system info: Linux 5.15.0-1016-gcp #21~20.04.1-Ubuntu SMP Fri Aug 5 12:53:07 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by konsttheogr** [comment]
![εικόνα](https://user-images.githubusercontent.com/60752156/185795392-0d9d6d34-dc7e-4c5a-9265-2a32383ea14c.png)
Im also getting this error but i cant locate it

**Comment by ooliver1** [comment]
> ![εικόνα](https://user-images.githubusercontent.com/60752156/185795392-0d9d6d34-dc7e-4c5a-9265-2a32383ea14c.png)
> Im also getting this error but i cant locate it

The nextcord version on your replit xontainer is not updated.

**Comment by konsttheogr** [comment]
> > ![εικόνα](https://user-images.githubusercontent.com/60752156/185795392-0d9d6d34-dc7e-4c5a-9265-2a32383ea14c.png)
> > Im also getting this error but i cant locate it
> 
> The nextcord version on your replit container is not updated.

Uh what should i do

**Comment by toolifelesstocode** [comment]
> > > ![εικόνα](https://user-images.githubusercontent.com/60752156/185795392-0d9d6d34-dc7e-4c5a-9265-2a32383ea14c.png)
> > > Im also getting this error but i cant locate it
> > 
> > 
> > The nextcord version on your replit container is not updated.
> 
> Uh what should i do

As Oliver said your nextcord version is outdated, it means that you need to **update your nextcord version**.

**Comment by ooliver1** [comment]
Not using latest, closing.
