### ISSUE TITLE
Implement the new documented forum channel features (e.g. tags)

### ISSUE THREAD

**Issue by ooliver1** [nextcord/nextcord#799]
### Summary

discord/discord-api-docs#5391

### What is the feature request for?

The core library

### The Problem

The above PR adds

**ForumChannel**
- `available_tags?`
- `applied_tags?`
- `default_reaction_emoji?`
- `default_thread_rate_limit_per_user?`

**ChannelFlags**
- `REQUIRE_TAG`

**ForumTag**
- `id`
- `name`
- `moderated`
- `emoji_id`
- `emoji_name`

**Thread**
- `applied_tags?`

### The Ideal Solution

Create a PR including all of the above features.

**Comment by Lorenzobattistela** [comment]
Hey, I am interested in this Issue to do my first OS contribution. But I quite did not understand how can I solve this problem. Could you help me? What should be done to solve this?

**Comment by Lorenzobattistela** [comment]
Sure, thanks for all the info! I will be working on it! You can assign me to this. Thanks.

**Comment by ooliver1** [comment]
@Lorenzobattistela assuming you are not working on this anymore, unassigning you.

**Comment by lol219** [comment]
Smh
