### ISSUE TITLE
Use `delete_message_seconds` for `Guild/Member.ban`

### ISSUE THREAD

**Issue by ooliver1** [nextcord/nextcord#800]
### Summary

discord/discord-api-docs#5219

### What is the feature request for?

The core library

### The Problem

The new way to set a duration is with seconds not days, this will likely be removed in API V11.

*`reason` being removed means nothing to us as since API V10, all routes use the `X-Audit-Log-Reason` header*

### The Ideal Solution

`seconds` refers to `delete_message_seconds`, same with `days`
- Expose `seconds` to the user
- deprecate `days` but translate the given value to `seconds` (so no breaking changes)
- raise a `ValueError` if both provided (like `embed` and `embeds` are both mutually exclusive)

**Comment by teaishealthy** [comment]
I can do this
