### ISSUE TITLE
Implement application commands API endpoints

### ISSUE THREAD

**Issue by MoonlightCapital** [nextcord/nextcord#81]
### Summary

The library needs to implement the endpoints provided to manage application commands

### What is the feature request for?

The core library

### The Problem

Currently, Discord provides some endpoints to register, update and delete application commands. This library does not implement any methods to access them through functions as now.

### The Ideal Solution

Write some async functions/classes to implement those endpoints: https://discord.com/developers/docs/interactions/application-commands#endpoints

This will be a lot helpful for the application commands developers as it's something that should still go into the core library.

### The Current Solution

Using raw HTTP requests made with some undocumented library parts, which is very inconvenient and messy for the end developer.

**Comment by jgayfer** [comment]
We already have these.

https://github.com/nextcord/nextcord/blob/7acfff9eaf4f5a4e27d616bb5c5b525ddd419b8a/nextcord/http.py#L1550-L1696

**Comment by MoonlightCapital** [comment]
Hold it right there

There are no methods exposed to the client class/a separate front-facing application class.

**Comment by jgayfer** [comment]
Sure. But should we be exposing raw HTTP methods? I'd argue that any reasonable implementation of slash commands would abstract this away from the user.

For anyone who really wants the raw HTTP methods, they can still call these directly.

**Comment by MoonlightCapital** [comment]
I wasn't talking about exposing those methods, I was more looking for an interface to the client class so end developers can do something like `bot.create_slash_command(some sort of data)` directly from the bot object, like any other API call.

**Comment by jgayfer** [comment]
Gotcha. The name of the ticket implies that we'd be implementing the endpoints directly, perhaps we could make that more clear.

Is the plan to have users manually call `create_slash_command` themselves for each command? Or would this be an interface that whatever flow we setup for command registration would use?

If it's the latter, whatever flow we build could likely get away with the raw HTTP methods. For the former, if we're having users directly call methods to register individual slash commands, I'm more curious about the overall implementation, as it doesn't sound very friendly to hit the endpoints yourself explicitly. I'd be more interested to see a decorator of sorts on the slash command handler, where the bot will register and found slash commands on login.

**Comment by MoonlightCapital** [comment]
I probably expressed myself in an ambiguous way, my bad.

The slash commands ext I'm working on will involve the developer calling a method to register a command or all of them, which will do some pre-processing before calling the API. Meanwhile, it's crucial to have some methods into the core lib to do this job, and maybe for developers who want a finer control on the registration operations.

**Comment by jgayfer** [comment]
I wouldn't say it's critical to expose these methods.

The thing to remember is that any time we expose a method publicly, people _will_ use it, even if it goes against the grain of a more desirable way to register slash commands.

I admit I'm coming at this with an outside perspective, but my ideal slash commands interface would be similar to how commands are currently defined.

- Register a command via a decorator
- On login / cog load, found commands are registered

Defining a command handler / listener separate from where slash commands are registered doesn't sound super friendly. Though as I said, I don't know your whole plan here, I'm just bike shedding.

**Comment by sairam4123** [comment]
> The slash commands ext I'm working on will involve the developer calling a method to register a command or all of them
That might not be the best, having it registered via decorator would be better option.

**Comment by MoonlightCapital** [comment]
Before deciding on the way slash command registration is performed, I'd like to have methods in the client that allow to get, register and update slash commands. This is the entire point of the issue. I discussed it with some other devs that are working on the slash commands part and they all agreed that slash commands cannot be registered unless we have client methods to do so. They are API methods for normal operations, say, creating a channel in a guild.

I'd like the validity of this issue to be reconsidered based on this new information.

**Comment by BenDev9** [comment]
As soon as it was announced that discord.py was getting discontinued, I started working on my own slash commands implementation, and I managed to make a decorator that works the same way at face value than the `discord.ext.commands.Command` decorator. It stores all of the commands, then it can translate all of them into the JSON asked for by the Discord endpoint, and send the necessary requests. I think this should be called within the `bot.run()` as then we'd have access to the token, which is needed for verification. I would be happy to help implement this into the library of you find it good enough.

**Comment by BenDev9** [comment]
As soon as it was announced that discord.py was getting discontinued, I started working on my own slash commands implementation, and I managed to make a decorator that works the same way at face value than the `discord.ext.commands.Command` decorator. It stores all of the commands, then it can translate all of them into the JSON asked for by the Discord endpoint, and send the necessary requests. I think this should be called within the `bot.run()` as then we'd have access to the token, which is needed for verification. I would be happy to help implement this into the library of you find it good enough.

**Comment by MoonlightCapital** [comment]
Okay, I already have made a method to translate it into JSON to register, now what? I can't send them to the API because there's no method to do so. Unless I use raw HTTP requests, that is.

**Comment by BenDev9** [comment]
Well, we'd probably have to write our own http requests, yes. But then again, that shouldn't be too difficult.

**Comment by alentoghostflame** [comment]
Would you say this is implemented by now, or is more work required?
