### ISSUE TITLE
Implement automod mention limits

### ISSUE THREAD

**Issue by ooliver1** [nextcord/nextcord#810]
### Summary

discord/discord-api-docs#5212, discord/discord-api-docs#5397

### What is the feature request for?

The core library

### The Problem

The above PRs are not implemented

### The Ideal Solution

- Add `mention_spam` to `AutoModerationTriggerType`.
- Add `mention_total_limit` to `AutoModerationTriggerMetadata`

**Comment by toolifelesstocode** [comment]
I can do this

**Comment by toolifelesstocode** [comment]
I cannot do this* :^)
