### ISSUE TITLE
Mutable defaults 

### ISSUE THREAD

**Issue by Skelmis** [nextcord/nextcord#815]
### Summary

Currently noticed this on http line 2252 with definition `files: List[File] = []`. This should be changed to use `None` and set within the method itself if not specified. For a better explanation see [here](https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/). Note its likely there exist other mutable defaults within the lib

### Reproduction Steps

N/A

### Expected Results

Non mutable defaults

### Actual Results

Mutable defaults

### Intents

N/A

### System Information

Master

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by DenverCoder1** [comment]
Is `create_followup_message` even called anywhere?

I noticed this earlier as well but I don't think it's critical as it seems in these cases (internal http) that all kwargs get passed every time so really they don't need defaults at all.

Still a good idea to fix though. In VS Code it shows warnings for all these (might be the sonarlint extension I have installed).

**Comment by Skelmis** [comment]
This also occurs when using Pycharm

**Comment by 10raw** [comment]
I would like to work on this issue

**Comment by 10raw** [comment]
@ooliver1 can you assign me this issue?

**Comment by Skelmis** [comment]
How is this looking, @10raw ?

**Comment by ooliver1** [comment]
This issue is back and available since it has been 2 months.

**Comment by EmreTech** [comment]
You have been assigned, @MaskDuck.
This issue will become available again if you don't open a PR within 2 months.

**Comment by Skelmis** [comment]
All files with mutable defaults (In top-level functions and non-nested methods) can be found using [this](https://workbin.dev/?id=1671619550449399) script I just threw together
