### ISSUE TITLE
Majority of methods in gateway.py are untyped

### ISSUE THREAD

**Issue by EmreTech** [nextcord/nextcord#816]
### Summary

The majority of methods defined in gateway.py have untyped parameters.

### What is the feature request for?

The core library

### The Problem

Not typing parameters in methods makes it hard to tell for static type checkers to infer what the type of each parameter is. For example, in the class method `DiscordWebSocket.from_client`, the parameters `gateway`, `shard_id`, `session`, and `sequence` cannot have their types inferred.

Additionally, this makes the code inconsistent compared to other pieces of code with all of their parameters typed, even the parameters for the private methods.

### The Ideal Solution

Type ***all*** parameters in methods defined in gateway.py. Even the private methods.

**Comment by doublevcodes** [comment]
Hello, I'd like to have a go at this as my first contribution to nextcord

**Comment by Skelmis** [comment]
Sounds amazing, I'll add you as the assignee.
