### ISSUE TITLE
Make it possible to describe command parameters using defaults

### ISSUE THREAD

**Issue by thesadru** [nextcord/nextcord#82]
### Summary

Use function parameter defaults to describe

### What is the feature request for?

nextcord.ext.commands

### The Problem

Generally, when attempting to describe an argument by either giving it a type, a proper default value, or even some slash command settings in the future you must either do that using explicit code or using the decorator itself. 

### The Ideal Solution

I suggest an approach similar to [fastapi](https://fastapi.tiangolo.com/) where fields are described using descriptor-like defaults. This is similar to a long-ignored pull request in the original repository except with more functionality and better extendability. It could also allow for accurate typing while keeping all the options.

### The Current Solution

This is currently done using annotations. That's generally a great approach but unusable for more complex approaches. 
My main problem is with converters. When you use a converter as an annotation it's not actually consistent with the actual type you'll get.

### Additional Context

An example of what we had to do before:
```py
def command(
    ctx: commands.Context,
    a: MyCustomConverter,
    b: commands.Greedy[converter_function],
    c: bool = False,
    *,
    rest: commands.clean_content() = ''
):
    ...
```
And a better solution:
```py
def command(
    ctx: commands.Context,
    a: float = Param(..., converter=MyCustomConverter.convert),
    b: List[int] = Param(..., converter=converter_function, greedy=True),
    c: bool = False,
    rest: str = Param('', rest=True, clean=True)
):
    ...
```
> the `...` are literal ellipsis

The functionality should still be consistent with the original pull request
```py
# from 
def command(ctx: commands.Context, member: discord.Member):
    member = member or ctx.author
    ...

# originally suggested
def command(ctx: commands.Context, member: discord.Member = Author()):
    ...

# ideal solution
author = Param(lambda ctx: ctx.member)
def command(ctx: commands.Context, member: discord.Member = author):
    ...
```
> author is now reusable and can even be included in the library itself.

### Possible signatures if anyone cares
```py
class Param:
    def __init__(
        self,
        # bot factories and actual types are allowed
        # Field can be a generic type but that will just cause more bad than good
        default: Union[Callable[[commands.Context], Any], commands.Converter, Any] = ...,
        optional: Optional[bool] = None,  # also based on if there is a default argument
        clean: bool = False,  # like commands.clean_content
        greedy: bool = False,  # like commands.Greedy[]
        rest: bool = False,  # like the very hacky keyword only parameter
    ) -> None:
        ...


# this function is the one that will be exported to allow for typing consistency
def Param(
    # in production a 1:1 copy of the  signature params for linters
    default: Union[Callable[[commands.Context], Any], commands.Converter, Any] = ...,
    optional: Optional[bool] = None,
    clean: bool = False,
    greedy: bool = False,
    rest: bool = False,
) -> Any:
    return nextcord.params.Param(default, optional, clean, greedy, rest)
```

### Benefits
- backward compatible. When a param is not defined the annotation is still used as the converter. When a converter parameter is not provided the annotation is used as the converter.
- Allows for other types and easier protocols. If the library provides a collection of converters it's easy to work with them.
- Not just `Param` has to be used. Other types such as `Flag` for flags like `--flag` can be used.
- This doesn't have to be limited to just normal commands, it can be implemented along with slash commands.
- And more maybe...

**Comment by TAG-Epic** [comment]
Hmmm not really a fan of this although this could be used for inline converters like this?

```py
@bot.command
async def test(ctx, arg: Converter(lambda text: text.upper())):
    ...
```

**Comment by thesadru** [comment]
The whole point of this proposal is to have correct annotations while still keeping all the settings. By doing this you still use incorrect annotations.

**Comment by thesadru** [comment]
This has been fully implemented in disnake so I think it's alright to close this. I wish the nextcord devs the best of luck!
