### ISSUE TITLE
cog_command_error For Slash/Application Commands

### ISSUE THREAD

**Issue by ItzBlueBerries** [nextcord/nextcord#825]
### Summary

Setting cog_command_error to work with Slash Commands instead of only prefix commands.

### What is the feature request for?

Application Commands

### The Problem

As the name says, `cog_command_error` cannot be used for Slash Commands in cogs. Using this is useful for error handlers on specific cogs, I have these set for almost all my cogs but for Slash Commands due to them not working properly.

### The Ideal Solution

Either adding support for `cog_command_error` with Slash Commands or creating a new version of it named `cog_application_error`. Either works, as long as they are run once the cog errors due to an application command.

### The Current Solution

Using `on_application_command_error` in your Events could solve this issue. Simply using it the same way as `on_command_error` but with `interaction: nextcord.Interaction` instead of `ctx`, etc. (Note: This does not work for Cogs, its for all Slash/Application Commands)

**Comment by Skelmis** [comment]
Note, this does not resolve the issue.

#826 updates the documentation to make this behavior obvious in the meantime while this issue is worked on
