### ISSUE TITLE
Slash command int type hint throws error for negative numbers

### ISSUE THREAD

**Issue by janasolo9** [nextcord/nextcord#856]
### Summary

Error for int type hint for slashcmds on 2.3

### Reproduction Steps

https://discord.com/channels/881118111967883295/1033104159584555189
Opening this ticket in place of someone else.

This person used PR #848, but this issue is on the master branch. https://github.com/nextcord/nextcord/blob/master/nextcord/application_command.py#L1619
https://github.com/nextcord/nextcord/blob/stable/nextcord/application_command.py#L1609

The person attempted to enter in -1 into a slash cmd arg that was type hinted to be an int and got `AttributeError: 'int' object has no attribute 'isdigit'`.

### Minimal Reproducible Code

```python
# error on NC 2.3 when entering negative integers
# this code works just fine on NC 2.2
bot = commands.Bot()

@bot.slash_command()
async def test(intr: nextcord.Interaction, num: int):
  await intr.send(num)
```

### Expected Results

The command in the minimal reproducible code should return the number, whether it's positive or negative.

### Actual Results

https://discord.com/channels/881118111967883295/1033104159584555189/1033104420935839884
Error traceback in this NC thread (I can't copy it because it's locked/closed)

### Intents

None

### System Information

N/A, but the error occurs on NC 2.3

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by DenverCoder1** [comment]
Seems like the "temporary fix" in #835 broke this.

I've opened a PR (#857) that should resolve this issue.
