### ISSUE TITLE
role connections

### ISSUE THREAD

**Issue by MaskDuck** [nextcord/nextcord#915]
### Summary

implement role connections which is new to discord.

### What is the feature request for?

The core library

### The Problem

https://github.com/discord/discord-api-docs/pull/5668/

### The Ideal Solution

implement it

**Comment by kingmigdor** [comment]
It's requiring a http endpoint like the interactions endpoint for http bots.

**Comment by ooliver1** [comment]
> Implement it

This provides no info to anyone without full knowledge of the API already. You could have mentioned the `role_connections_verification_url` field, `Application Role Connection Metadata Object` (and all other types), `Get Application Role Connection Metadata Records` and all other routes, and how this all relates to nextcord itself.
