### ISSUE TITLE
Can no longer pass nextcord.Member or nextcord.User to prefix commands

### ISSUE THREAD

**Issue by brah** [nextcord/nextcord#922]
### Summary

Commands called by @client.command() can no longer use nextcord.User as a parameter

### Reproduction Steps

Make two commands: one using slash commands and featuring nextcord.User/Member as parameters
One will not run, not error, not even breakpoint on the first line. It won't run whatsoever

Make it a slash command and it accepts perfectly fine and works as intended

### Minimal Reproducible Code

```python
@nextcord.slash_command()
    async def avatar(self, ctx, user: nextcord.Member = None):
        if user is None:
            user_avatar_url = ctx.author.display_avatar
        else:
            user_avatar_url = user.display_avatar
        await ctx.send(user_avatar_url)

    @commands.command()
    async def avatar(self, ctx, user: nextcord.Member = None):
        if user is None:
            user_avatar_url = ctx.author.display_avatar
        else:
            user_avatar_url = user.display_avatar
        await ctx.send(user_avatar_url)
```
(commands are named the same for demonstration, I had two existing commands using nextcord.Member and neither work anymore without slash-ifying them)

### Expected Results

nextcord.Member should (used to) pass perfectly fine to traditional prefix commands

### Actual Results

The command doesn't run whatsoever

### Intents

All

### System Information

- Python v3.11.0-final
- nextcord v2.3.2-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.22621
(using Windows 11, not sure why output shows 10)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I highly expect this to be a Discord side thing, but can be better handled on nextcord error end (if possible)
Only other changes I made before it broke were (updating nextcord, upgrading python to 3.11)

**Comment by brah** [comment]
> Firstly, are there any errors that occur when you run the command? Secondly, there is a chance it's because you have 2 functions named the same thing, which can cause conflict, but I am not _too_ sure

No errors, no breakpoints, nothing really of substance
They're named the same just for demonstration (one works, one doesn't anymore) - edited the post to clarify that

**Comment by DenverCoder1** [comment]
Also I can't reproduce the issue you are facing so the problem is probably **not** related to the nextcord.Member converter.

**Comment by brah** [comment]
> Slash commands do not take `ctx` (Context), they instead use `Interaction` which does not have an `author` attribute since it's not a message, but it does have a `user` attribute you would use instead.
> 
> Here's one way I might rewrite your code:
> 
> ```python
> from typing import Optional
> import nextcord
> 
> # ... in your cog class:
> 
> @nextcord.slash_command()
> async def avatar(self, interaction: nextcord.Interaction, user: Optional[nextcord.Member]):
>     user_avatar = user.display_avatar if user else interaction.user.display_avatar
>     await interaction.send(user_avatar.url)
> ```
> 
> **Note the use of `interaction.user` rather than `ctx.author`.**

Thanks, I don't typically use slash commands so don't know their ideals, will update mine



> Also I can't reproduce the issue you are facing so the problem is probably **not** related to the nextcord.Member converter.

That's really weird then. I even tried rolling back to nextcord 2.0.0 and using python 3.10 but still nothing.
Could it be how I load my cogs? (it also doesn't work in entry file, so not sure about that) but:
```for filename in os.listdir('./cogs/'):
    if filename.endswith('.py'):
        client.load_extension(f'cogs.{filename[:-3]}')```

Or maybe permissions? (Bot's role has admin perm, intents.all(). Maybe something in discord dev portal? Is there a good way to debug this?)
If there's anything else I can provide that's helpful let me know

**Comment by EmreTech** [comment]
> (Bot's role has admin perm, intents.all(). Maybe something in discord dev portal? Is there a good way to debug this?)

I don't think it has to do with the Discord dev portal because you would be getting an error about requesting intents that you haven't allowed your bot to have via the Discord dev portal.

Have you tried some debug print statements to see when exactly the command stops running (if it's even running at all)?

**Comment by brah** [comment]
> > (Bot's role has admin perm, intents.all(). Maybe something in discord dev portal? Is there a good way to debug this?)
> 
> I don't think it has to do with the Discord dev portal because you would be getting an error about requesting intents that you haven't allowed your bot to have via the Discord dev portal.
> 
> Have you tried some debug print statements to see when exactly the command stops running (if it's even running at all)?

Yeah. In a help thread in the discord I was discussing this
Breakpoints & prints and the command wouldn't even run a first line print("test") if the nextcord.Member parameter was passed (if it's optional and you pass None, it will run fine - without a nextcord.Member ofc)
Even if nextcord.Member is passed later (even if not specifying type in parameters/elsewhere)
```    @commands.command(aliases=['av'])
    async def avatar(self, ctx, user):
        print(user)
        ```
        still nothing. I'm fine to share more/all code in discord if it'll help. really thought I wouldn't be alone with this issue lol but since rolling back nextcord fixed nothing and it clearly isn't a discord API end thing, I'm pretty confused

**Comment by ooliver1** [comment]
> (commands are named the same for demonstration, I had two existing commands using nextcord.Member and neither work anymore without slash-ifying them)

Then this isn't minimal reproducible code, since one overwrites the other. Please provide minimal reproducible code which requires just passing a token and shows this behaviour.

**Comment by ooliver1** [comment]
No minimal response, `Member` and `User` work for me.
