### ISSUE TITLE
Re-add selfbot support

### ISSUE THREAD

**Issue by dekrypted** [nextcord/nextcord#923]
### Summary

Recently all Discord frameworks removed support for selfbots. I want it back!

### What is the feature request for?

The core library

### The Problem

The problem is that when doing `client.run(TOKEN, bot=False)` the `bot` keyword no longer works because all frameworks decided to remove support for selfbots. I know selfbots are not permitted by TOS but come on, just re-add support.

### The Ideal Solution

Re-adding support

### The Current Solution

Once again, re-adding support

### Additional Context

N/A

**Comment by toolifelesstocode** [comment]
Self-botting is against Discord's Terms of Services. Which is why every library has removed that. It will not be added back, as, once again, it is against Discord's Terms of Service.

**Comment by dekrypted** [comment]
"I know selfbots are not permitted by TOS but come on, just re-add support."

Whatever, maybe I'll make my own fork.

**Comment by DenverCoder1** [comment]
In order to be listed among [Discord API Community Resources](https://github.com/discord/discord-api-docs/blob/main/docs/topics/Community_Resources.md#discord-libraries) and have a Verified and Partnered support server, we need to abide by the TOS.
