### ISSUE TITLE
Reword docs for `PublicUserFlags.cerified_moderator`

### ISSUE THREAD

**Issue by ooliver1** [nextcord/nextcord#935]
### Summary

Reword the docstring for `cerified_moderator` to relay the recent change to the badge.

### What is the feature request for?

The core library

### The Problem

Discord Moderator Discord/Moderator Program was recently shut down, the docs should replicate this.
https://github.com/nextcord/nextcord/blob/22eb5d169f6a05f2c813d72a158972a0ba3d7dc1/nextcord/flags.py#LL460

### The Ideal Solution

Reword the docs to mention they are an alumni since that is what the badge hover text shows.

### Additional Context

discord/discord-api-docs#5695

**Comment by toolifelesstocode** [comment]
I would like to try this 🙂
