### ISSUE TITLE
ImportError: cannot import name 'StringSelct' from 'nextcord.ui' (C:\Program Files\Python39\lib\site-packages\nextcord\ui\__init__.py)

### ISSUE THREAD

**Issue by aliencaocao** [nextcord/nextcord#951]
### Summary

Cannot import despite docs stating it is under nextcord.ui.StringSelect

### Reproduction Steps

```from nextcord.ui import View, Button, StringSelct```

### Minimal Reproducible Code

```python
nextcord.ui import View, Button, StringSelct
```

### Expected Results

Successful import

### Actual Results

```ImportError: cannot import name 'StringSelct' from 'nextcord.ui' (C:\Program Files\Python39\lib\site-packages\nextcord\ui\__init__.py)```

### Intents

None

### System Information

```- Python v3.9.13-final
- nextcord v2.3.2-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19045```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

**Comment by EmreTech** [comment]
This is caused by a typo as it's `StringSelect`, not `StringSelct`.
Please use our Discord server for support next time.

**Comment by aliencaocao** [comment]
Sorry my bad. I had this issue before upgrading to 2.3.2 then I thought it is the same after I upgraded,
