### ISSUE TITLE
RawMessageDeleteEvent documentation has different behavoir than the library itself

### ISSUE THREAD

**Issue by SteffoSpieler** [nextcord/nextcord#953]
### Summary

Documentation has message_ids, Library has message_id

### Reproduction Steps

1. Create a Listener that is using `on_raw_message_delete`
2. Import `RawMessageDeleteEvent`
3. Try to use message_ids (that is shown in the docs)
4. See warning as it doesn't exist

### Minimal Reproducible Code

```python
@Cog.listener()
async def on_raw_message_delete(self, payload: RawMessageDeleteEvent):
    for message_id in payload.message_ids:
```

### Expected Results

I expect to see the same arguments in the library as in the [documentation](https://docs.nextcord.dev/en/stable/api.html#nextcord.RawMessageDeleteEvent).

### Actual Results

The documentation has [message_ids](https://docs.nextcord.dev/en/stable/api.html#nextcord.RawBulkMessageDeleteEvent.message_ids) and the library has message_id.

### Intents

Intents(guilds=True, members=True, bans=False, emojis=True, integrations=False, webhooks=False, invites=False, voice_states=True, presences=False, messages=True, message_content=True, reactions=True, typing=False)

### System Information

- Python v3.9.13-final
- nextcord v2.3.2-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

That's not directly a "bug", but it's imo the category it fits the best?

**Comment by ooliver1** [comment]
I don't think this is an issue. You are using `RawMessageDeleteEvent` - `on_raw_message_delete`, but are referencing the documentation to `RawBulkMessageDeleteEvent` - `on_raw_bulk_message_delete`, since bulk has multiple messages.

**Comment by SteffoSpieler** [comment]
oh true. I missed that as when I clicked on the type `RawMessageDeleteDelete`, I got to https://docs.nextcord.dev/en/stable/api.html#nextcord.RawMessageDeleteEvent, which then shows the bulk version (without the title) for me. But only when clicking it. When pressing F5, I jump to the correct one 🤔 
I use Firefox fyi

**Comment by ooliver1** [comment]
Works just fine for me on Firefox aurora `109.0b3 (64-bit)` when clicking the type from `on_raw_message_delete`.

**Comment by SteffoSpieler** [comment]
oh well... then I think it's just a weird bug with opening in a new tab as I only can reproduce it sometimes - with the same steps.
I'll close this issue now.
