### ISSUE TITLE
Global Checks for Application Commands

### ISSUE THREAD

**Issue by RPrime2003** [nextcord/nextcord#956]
### Summary

Adding global checks for application commands

### What is the feature request for?

Application commands

### The Problem

After some looking around for a way to implement a global check for application commands (much like the [global checks for context commands](https://docs.nextcord.dev/en/stable/ext/commands/commands.html#global-checks)), it seems there isn't a way to do a global check of all slash commands. 

### The Ideal Solution

This feature would act just like [global checks](https://docs.nextcord.dev/en/stable/ext/commands/commands.html#global-checks) for context commands except it would apply to application commands.

**Comment by Soheab** [comment]
This is apparently already a thing but not as a decorator: https://docs.nextcord.dev/en/stable/ext/commands/api.html#nextcord.ext.commands.Bot.add_application_command_check
