### ISSUE TITLE
Plan to incorporate other abandoned modules into Nextcord.

### ISSUE THREAD

**Issue by redcreeper14385** [nextcord/nextcord#96]
At the moment, all extension modules created by https://github.com/Ext-Creators (such as discord-ext-ipc) are abandoned due to the shutting down of discord.py. We can incorporate these modules into Nextcord in two ways:

1. Incorporate them as extra modules within this repo, under the `ext` folder
2. Have them as separate repos in the organisation

I recommend option 1 as it would make Nextcord one of the largest Discord APIs around and would put us ahead significantly.

**Comment by Sn1F3rt** [comment]
@redcreeper14385 I'm already working on that, in fact, the IPC is ready and it'll shortly be imported into the organization. However, I recommend that the external modules remain outside of the main repository till a stable version of both nextcord and the ext modules are released, tried, and tested by the community.

**Comment by redcreeper14385** [comment]
> @redcreeper14385 I'm already working on that, in fact, the IPC is ready and it'll shortly be imported into the organization. However, I recommend that the external modules remain outside of the main repository till a stable version of both nextcord and the ext modules are released, tried, and tested by the community.

I think this pre-release stage would be perfect for ensuring that we can incorporate those modules into `ext`

**Comment by Sn1F3rt** [comment]
Ensuring is fine, I just wanted the modules to be a bit tried and tested by developers and enhanced based on their feedback. I had a talk with the original author of `discord-ext-ipc` and he pointed out that the code isn't perfect and needs some radical improvements. I shall post them as an issue that needs help once they're up on the org. Little patience can definitely pay off.

**Comment by sairam4123** [comment]
In my opinion, instead of merging up all into one big library we should keep them as separate repositories here. That would keep the download size low.

**Comment by vcokltfre** [comment]
+1 for not merging into this repository. We should be maintaining a Discord library/bot framework. Everything in here right now is fairly closely related to how the vast majority of bots function, or is there for API coverage, and thus is needed. Things like IPC are comparatively very rare usecases, and are best suited to remaining outside the main library repository.

**Comment by TAG-Epic** [comment]
This has now been done with ext-menus and ext-ipc and soon ext-alternatives.
