### ISSUE TITLE
Multiprocess Sharding

### ISSUE THREAD

**Issue by sairam4123** [nextcord/nextcord#99]
### Link

https://github.com/Rapptz/discord.py/issues/1416

**Comment by ooliver1** [comment]
I do not see much point in a library implementing an opinionated version of this. When a bot is large enough for multi process sharding to be relevant, the bot will require vastly different multi process communication implementations.
Already doing multi process sharding is possible with nextcord by using `shard_ids` and `shard_tootal` in `AutoShardedClient`/`commands.AutoShardedBot`.
